--1-1 CRM Export

SET SCHEMA GAUSS_BIGD;

DROP TABLE GAUSS_BIGD.MSCRM_ACCOUNTS IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_ACTIVITYREPORTS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_APPLICATIONS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_APPOINTMENTS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_COMMENTS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_COMPETITORS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_CONTACTS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_EMAILS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_LEADS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_OPPORTUNITIES   IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_OPPORTUNITYCOMPETITORS   IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_OPPORTUNITYPRODUCTS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_PHONECALLS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_PRODUCTUSAGES IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_QUOTEDETAILS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_QUOTES  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_RPCL  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_SALESTEAMMEMBERS  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_SAMPLES  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_SOURCE  IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_TASKS IF EXISTS;
DROP TABLE GAUSS_BIGD.MSCRM_USAGEDETAILS  IF EXISTS;


CREATE TABLE GAUSS_BIGD.MSCRM_ACCOUNTS
(
	URL 					varchar(301) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	ACCOUNTGUID 			varchar(36) 			NOT NULL,
	ACCOUNTERPID 			integer 				NULL,
	ACCOUNTNAME 			character varying(160) 	NULL,
	CHANNEL 				character varying(100) 	NULL,
	BUSINESSUNIT 			character varying(160) 	NULL,
	LENERPID 				integer 				NULL,
	OLEERPID 				integer 				NULL,
	OLENAME 				character varying(100) 	NULL,
	STATUS					varchar(10)				NULL, 
	STATUSREASON			varchar(10)				NULL,
	BUYINGSTATUS 			character varying(100) 	NULL,
	ACCOUNTTYPEDESC 		varchar(50) 			NULL,
	PROSPECTVALIDATIONSTATUS varchar(50)			NULL,
	SEGMENT 				varchar(100) 			NULL,
	FISCALACCOUNTGUID 		varchar(36) 			NULL,
	PRIMARYCONTACT 			character varying(160) 	NULL,
	LEGALADDRESSERPID 		integer 				NULL,
	LEGALADDRESS 			character varying(200) 	NULL,
	PRIMARYADDRESSERPID 	integer 				NULL,
	PRIMARYADDRESS 			character varying(200) 	NULL,
	ADDRESSLINE1 			character varying(250)	NULL,
	ADDRESSLINE2 			character varying(250) 	NULL,
	POSTALCODE 				character varying(20) 	NULL,
	CITY 					character varying(80) 	NULL,
	PROVINCE 				character varying(50) 	NULL,
	COUNTY 					character varying(50) 	NULL,
	COUNTRY 				character varying(100) 	NULL,
	TERRITORYERPID 			integer 				NULL,
	TERRITORY 				character varying(200) 	NULL,
	PHONE 					character varying(50) 	NULL,
	FAX 					character varying(50) 	NULL,
	EMAIL 					character varying(100)	NULL,
	WEBSITEURL 				character varying(200) 	NULL,
	LANGUAGEERPID 			integer 				NULL,
	LANGUAGE 				character varying(100) 	NULL,
	NUMBEROFEMP 			integer 				NULL,
	NUMBEROFMACH 			integer 				NULL,
	COMPANYCOMMENT 			character varying(32000) 	NULL,
	UOMERPID 				smallint 				NULL,
	UOMNAME 				character varying(100) 	NULL,
	PREFERREDCURR 			character varying(100) 	NULL,
	TRANSACTIONCURR 		character varying(100) 	NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	CREATEDON 				timestamp 				NOT NULL,
	CREATEDBY 				character varying(200) 	NOT NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NOT NULL,
	MODIFIEDBY 				character varying(200) 	NOT NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL,
	SALESPERSON 			character varying(200) 	NULL,
	SALESPERSONRAVID 		varchar(10) 			NULL,
	SALESPERSONERPID 		integer 				NULL,
	CSR 					character varying(200) 	NULL,
	CSRRAVID 				varchar(10) 			NULL,
	CSRERPID 				integer 				NULL
   ,CONSTRAINT CRMACCOUNTS_PK PRIMARY KEY (ACCOUNTGUID,SOURCEID)
)
DISTRIBUTE ON (ACCOUNTGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_ACTIVITYREPORTS 
(
	URL	 				varchar(312) 			NULL,	
	SOURCEID	 		smallint 				NOT NULL,
	ACTIVITYREPORTGUID	varchar(36) 			NOT NULL,
	ACTIVITYREPORT	 	character varying(250) 	NULL,
	ACCOUNTGUID	 		varchar(36) 			NULL,
	ACCOUNTERPID	 	integer 				NULL,
	ACCOUNT	 			character varying(160) 	NULL,
	BUSINESSUNIT	 	character varying(160) 	NULL,
	STATUS	 			varchar(20) 			NULL,
	STATUSREASON	 	varchar(20) 			NULL,
	CUSTOMERCONNECTION	integer 				NULL,
	OBJECTIVES	 		character varying(2000) 	NULL,
	MAINFINDINGS	 	character varying(2000) 	NULL,
	REGARDINGENTITY	 	character varying(350) 	NULL,
	REGARDINGGUID		varchar(36)				NULL, 
	ACTIVITYTYPE	 	character varying(128) 	NULL,
	ACTIVITYGUID	 	varchar(36)			 	NULL,
	ORIGINATINGOPPORTUNITYGUID	varchar(36)		NULL, 
	OWNER	 			character varying(200) 	NULL,
	OWNERRAVID	 		varchar(10) 			NULL,
	OWNERPERSERPID	 	integer 				NULL,
	CREATEDON	 		timestamp 				NOT NULL,
	CREATEDBY	 		character varying(200) 	NOT NULL,
	CREATEDRAVID	 	varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON	 		timestamp 				NOT NULL,
	MODIFIEDBY	 		character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 	varchar(10) 			NULL,
	MODIFIEDPERSERPID	integer 				NULL,
	MAXCHANGEDDATE	 	timestamp 				NOT NULL
   ,CONSTRAINT CRMACTIVITYREPORTS_PK PRIMARY KEY (ACTIVITYREPORTGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYREPORTGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_APPLICATIONS 
(
	URL	 					varchar(309) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	APPLICATIONGUID	 		varchar(36) 			NOT NULL,
	APPLICATIONNAME	 		character varying(255) 	NULL,
	STATUS	 				varchar(20) 			NULL,
	STATUSREASON	 				varchar(20) 			NULL,
	LOCALLANGUAGENAME	 	character varying(255) 	NULL,
	ACCOUNTGUID	 			varchar(36) 			NULL,
	ACCOUNTERPID	 		integer 				NULL,
	BUSINESSUNIT	 		character varying(160) 	NULL,
	MEDICALAPPLICATION	 	varchar(10) 			NULL,
	CONFIDENTIALAPPLICATION	varchar(10) 			NULL,
	MARKET	 				character varying(100) 	NULL,
	SEGMENT	 				character varying(100) 	NULL,
	SUBSEGMENT	 			character varying(100) 	NULL,
	PROCESSINGMETHODERPID	integer 				NULL,
	PROCESSINGMETHOD	 	character varying(100) 	NULL,
	OEMERPID	 			integer 				NULL,
	OEM	 					character varying(100) 	NULL,
	DESCRIPTION	 			character varying(800) NULL,
	OPPORTUNITYGUID         character varying(36)	NULL,
	OPPORTUNITY				character varying(300) 	NULL,
	EAQOPPORTUNITY	 		decimal(15, 4) 			NULL,
	EAQOPPLASTUPDATE	 	timestamp 				NULL,
	TOTALEAQUSAGE	 		decimal(15, 4) 			NULL,
	TOTALEAQUSAGELASTUPDATE	timestamp 				NULL,
	EAQOURSHARE	 			decimal(15, 4) 			NULL,
	EAQOURSHARELASTUPDATE	timestamp 				NULL,
	OWNER	 				character varying(200) 	NULL,
	OWNERRAVID	 			varchar(10) 			NULL,
	OWNERPERSERPID	 		integer 				NULL,
	CREATEDON	 			timestamp 				NOT NULL,
	CREATEDBY	 			character varying(200) 	NOT NULL,
	CREATEDRAVID	 		varchar(10) 			NULL,
	CREATEDPERSERPID	 	integer 				NULL,
	MODIFIEDON	 			timestamp 				NOT NULL,
	MODIFIEDBY	 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 		varchar(10) 			NULL,
	MODIFIEDPERSERPID	 	integer 				NULL,
	MAXCHANGEDDATE	 		timestamp 				NOT NULL 
   ,CONSTRAINT CRMAPPLICATIONS_PK PRIMARY KEY (APPLICATIONGUID,SOURCEID)
)
DISTRIBUTE ON (APPLICATIONGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_APPOINTMENTS 
(
	URL	 				varchar(305) 			NULL,
	SOURCEID	 		smallint 				NOT NULL,
	ACTIVITYGUID	 	varchar(36)  			NOT NULL,
	ACTIVITYTYPE	 	varchar(20) 			NULL,
	REGARDINGENTITYGUID	varchar(36)  			NULL,
	REGARDINGENTITY	 	varchar(50) 			NULL,
	REGARDING	 		character varying(300)	NULL,
	BUSINESSUNIT	 	character varying(160) 	NULL,
	STATUS	 			varchar(30) 			NULL,
	STATUSREASON		varchar(30) 			NULL,
	APPOINTMENTTYPE	 	varchar(50) 			NULL,
	PRIORITY	 		varchar(20) 			NULL,
	REQUIREDATTENDEES	character varying(400) 	NULL,
	OPTIONALATTENDEES	character varying(400) NULL,
	ORGANIZER	 		character varying(400) 	NULL,
	SUBJECT	 			character varying(1000) 	NULL,
	SCHEDULEDSTART	 	timestamp 				NULL,
	SCHEDULEDDURATION	integer 				NULL,
	SCHEDULEDEND	 	timestamp 				NULL,
	ACTUALSTART	 		timestamp 				NULL,
	ACTUALDURATION	 	integer 				NULL,
	ACTUALEND	 		timestamp 				NULL,
	ACTIVITYREPORTGUID	varchar(36)  			NULL,
	ACTIVITYREPORT	 	character varying(250) 	NULL,
	LOCATION	 		character varying(200) 	NULL,
	OWNER	 			character varying(200) 	NULL,
	OWNERRAVID	 		varchar(10) 			NULL,
	OWNERPERSERPID	 	integer 				NULL,
	CREATEDON	 		timestamp 				NOT NULL,
	CREATEDBY	 		character varying(200) 	NOT NULL,
	CREATEDRAVID	 	varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON	 		timestamp 				NOT NULL,
	MODIFIEDBY	 		character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 	varchar(10) 			NULL,
	MODIFIEDPERSERPID	integer 				NULL,
	MAXCHANGEDDATE	 	timestamp 				NOT NULL
   ,CONSTRAINT CRMAPPOINTMENTS_PK PRIMARY KEY (ACTIVITYGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_COMMENTS 
(
	URL	 				varchar(305) 			NULL,
	SOURCEID	 		smallint				NOT NULL,
	ACTIVITYGUID	 	varchar(36) 			NOT NULL,
	ACTIVITYTYPE	 	varchar(20) 			NULL,
	REGARDINGENTITYGUID	varchar(36) 			NULL,
	REGARDINGENTITY	 	varchar(50) 			NULL,
	REGARDING	 		character varying(300) 	NULL,
	BUSINESSUNIT	 	character varying(160) 	NULL,
	STATUS	 			varchar(30) 			NULL,
	STATUSREASON		varchar(30) 			NULL,
	COMMENTTYPE	 		varchar(50) 			NULL,
	PRIORITY	 		varchar(20) 			NULL,
	HIGHLOW	 			varchar(20) 			NULL,
	COMMENT	 			character varying(200) 	NULL,
	DESCRIPTION	 		character varying(2000) 	NULL,
	ACTIVITYREPORTGUID	varchar(36) 			NULL,
	ACTIVITYREPORT	 	character varying(250) 	NULL,
	OWNER	 			character varying(200) 	NULL,
	OWNERRAVID	 		varchar(10) 			NULL,
	OWNERPERSERPID	 	integer 				NULL,
	CREATEDON	 		timestamp 				NOT NULL,
	CREATEDBY	 		character varying(200) 	NOT NULL,
	CREATEDRAVID	 	varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON	 		timestamp 				NOT NULL,
	MODIFIEDBY	 		character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 	varchar(10) 			NULL,
	MODIFIEDPERSERPID	integer 				NULL,
	MAXCHANGEDDATE		timestamp 				NOT NULL
   ,CONSTRAINT CRMCOMMENTS_PK PRIMARY KEY (ACTIVITYGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_COMPETITORS 
(
	URL	 				varchar(304) 			NULL,
	SOURCEID	 		smallint 				NOT NULL,
	COMPETITORGUID		varchar(36) 			NOT NULL,
	COMPETITORERPID		integer 				NULL,
	COMPETITORNAME		character varying(100)	NULL,
	WEBSITE	 			character varying(200) 	NULL,
	STRENGTHS	 		character varying(200) NULL,
	WEAKNESSES	 		character varying(200) NULL,
	CURRENCY	 		character varying(100) 	NULL,
	ADDRESSLINE1	 	character varying(250) 	NULL,
	ADDRESSLINE2	 	character varying(250) 	NULL,
	ADDRESSLINE3	 	character varying(250) 	NULL,
	CITY	 			character varying(80) 	NULL,
	PROVINCE	 		character varying(50) 	NULL,
	POSTALCODE	 		character varying(20) 	NULL,
	COUNTRY	 			character varying(80) 	NULL,
	OPPORTUNITY	 		character varying(300) 	NULL,
	CREATEDON	 		timestamp 				NOT NULL,
	CREATEDBY	 		character varying(200) 	NOT NULL,
	CREATEDRAVID	 	varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON	 		timestamp 				NOT NULL,
	MODIFIEDBY	 		character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 	varchar(10) 			NULL,
	MODIFIEDPERSERPID	integer 				NULL,
	MAXCHANGEDDATE	 	timestamp 				NOT NULL	
   ,CONSTRAINT CRMCOMPETITORS_PK PRIMARY KEY (COMPETITORGUID,SOURCEID)
)
DISTRIBUTE ON (COMPETITORGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_CONTACTS 
(
	URL	 					varchar(301) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	CONTACTGUID				varchar(36) 			NOT NULL,
	ACCOUNTGUID	 			varchar(36) 			NULL,
	ACCOUNTERPID	 		integer 				NULL,
	ACCOUNTNAME	 			character varying(160) 	NULL,
	LENERPID	 			integer 				NULL,
	OLEERPID	 			integer 				NULL,
	OLENAME	 				character varying(100) 	NULL,
	WEBSITE	 				character varying(200) 	NULL,
	EXISTINGCONTACT	 		character varying(160) 	NULL,
	FIRSTNAME	 			character varying(50) 	NULL,
	LASTNAME	 			character varying(100) 	NULL,
	SALUTATION	 			varchar(20) 			NULL,
	CONTACTTYPEERPID	 	integer 				NULL,
	CONTACTTYPE	 			character varying(100) 	NULL,
	DEPARTMENT	 			character varying(350) 	NULL,
	JOBTITLE	 			character varying(100) 	NULL,
	EMAIL	 				character varying(100) 	NULL,
	BUSINESSPHONE	 		character varying(50) 	NULL,
	MOBILEPHONE	 			character varying(50) 	NULL,
	FAX	 					character varying(50) 	NULL,
	GENDER	 				varchar(20)				NULL,
	PERSONALNOTES	 		character varying(1000) 	NULL,
	STATUS	 				varchar(20) 			NULL,
	STATUSREASON	 		varchar(20) 			NULL,
	CHOOSEADDRESS	 		varchar(50) 			NULL,
	ADDRESSERPID	 		integer 				NULL,
	STREET1	 				character varying(250) 	NULL,
	STREET2	 				character varying(250) 	NULL,
	POSTALCODE	 			character varying(20) 	NULL,
	CITY					character varying(100) 	NULL,
	PROVINCE	 			character varying(100) 	NULL,
	COUNTRYERPID	 		integer	 				NULL,
	COUNTRY	 				character varying(100) 	NULL,
	PREFERREDCONTACTMETHOD	varchar(30) 			NULL,
	DONOTEMAIL	 			varchar(30) 			NULL,
	DONOTBULKEMAIL	 		varchar(30) 			NULL,
	DONOTPHONE	 			varchar(30) 			NULL,
	DONOTFAX	 			varchar(30) 			NULL,
	DONOTPOSTMAIL	 		varchar(30) 			NULL,
	DONOTBULKPOSTMAIL	 	varchar(30) 			NULL,
	OWNER	 				character varying(200) 	NULL,
	OWNERRAVID	 			varchar(10) 			NULL,
	OWNERPERSERPID	 		integer 				NULL,
	CREATEDON	 			timestamp 				NOT NULL,
	CREATEDBY	 			character varying(200) 	NOT NULL,
	CREATEDRAVID	 		varchar(10) 			NULL,
	CREATEDPERSERPID		integer 				NULL,
	MODIFIEDON	 			timestamp 				NOT NULL,
	MODIFIEDBY	 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 		varchar(10) 			NULL,
	MODIFIEDPERSERPID		integer 				NULL,
	MAXCHANGEDDATE	 		timestamp 				NOT NULL	
   ,CONSTRAINT CRMCONTACTS_PK PRIMARY KEY (CONTACTGUID,SOURCEID)
)
DISTRIBUTE ON (CONTACTGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_EMAILS 
(
	URL	 				varchar(299) 			NULL,
	SOURCEID			smallint 				NOT NULL,
	ACTIVITYGUID	 	varchar(36)  			NOT NULL,
	ACTIVITYTYPE	 	varchar(20) 			NULL,
	REGARDINGENTITYGUID	varchar(36)  			NULL,
	REGARDINGENTITY	 	varchar(50) 			NULL,
	REGARDING	 		character varying(300) 	NULL,
	BUSINESSUNIT	 	character varying(160) 	NULL,
	STATUS	 			varchar(20) 			NULL,
	STATUSREASON		varchar(20) 			NULL,
	DIRECTION	 		varchar(20) 			NULL,
	PRIORITY	 		varchar(20) 			NULL,
	SUBJECT	 			character varying(800) 	NULL,
	EMAILFROM	 		character varying(400) 	NULL,
	EMAILTO	 			character varying(1000) NULL,
	EMAILCC	 			character varying(1000) NULL,
	EMAILBCC	 		character varying(500) NULL,
	SCHEDULEDSTART	 	timestamp 				NULL,
	SCHEDULEDDURATION	integer 				NULL,
	SCHEDULEDEND	 	timestamp 				NULL,
	ACTUALSTART	 		timestamp 				NULL,
	ACTUALDURATION	 	integer 				NULL,
	ACTUALEND	 		timestamp 				NULL,
	OWNER	 			character varying(200) 	NULL,
	OWNERRAVID	 		varchar(10) 			NULL,
	OWNERPERSERPID	 	integer 				NULL,
	CREATEDON	 		timestamp 				NOT NULL,
	CREATEDBY	 		character varying(200) 	NOT NULL,
	CREATEDRAVID	 	varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON	 		timestamp 				NOT NULL,
	MODIFIEDBY	 		character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 	varchar(10) 			NULL,
	MODIFIEDPERSERPID	integer 				NULL,
	MAXCHANGEDDATE	 	timestamp 				NOT NULL	
   ,CONSTRAINT CRMEMAILS_PK PRIMARY KEY (ACTIVITYGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_LEADS 
(
	URL	 					varchar(298) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	LEADGUID	 			varchar(36) 			NOT NULL,
	ACCOUNTGUID	 			varchar(36) 			NULL,
	ACCOUNTERPID	 		integer 				NULL,
	ACCOUNTNAME	 			character varying(160) 	NULL,
	LENERPID	 			integer 				NULL,
	OLEERPID	 			integer 				NULL,
	OLENAME	 				character varying(100) 	NULL,
	UOMSYSTEMERPID	 		integer 				NULL,
	UOMSYSTEM	 			character varying(100) 	NULL,
	PREFERREDCURRENCY	 	character varying(100) 	NULL,
	VATNO	 				character varying(100) 	NULL,
	COUNTRYERPID	 		integer 				NULL,
	COUNTRY	 				character varying(100) 	NULL,
	WEBSITE	 				character varying(200) 	NULL,
	LANGUAGEERPID	 		integer 				NULL,
	LANGUAGE	 			character varying(100) 	NULL,
	EXISTINGCONTACT	 		character varying(160) 	NULL,
	FIRSTNAME	 			character varying(50) 	NULL,
	LASTNAME	 			character varying(50) 	NULL,
	SALUTATION	 			varchar(20) 			NULL,
	JOBTITLE	 			character varying(100) 	NULL,
	BUSINESSPHONE	 		character varying(50) 	NULL,
	MOBILEPHONE	 			character varying(20) 	NULL,
	EMAIL	 				character varying(100) 	NULL,
	LEADSOURCE	 			character varying(350) 	NULL,
	TERRITORYERPID	 		integer 				NULL,
	TERRITORY	 			character varying(200) 	NULL,
	RATING	 				varchar(20) 			NULL,
	STATUS		 			varchar(20) 			NULL,
	STATUSREASON 			varchar(40) 			NULL,
	PROVINCEERPID	 		integer 				NULL,
	PROVINCE	 			character varying(100) 	NULL,
	CITY	 				character varying(80) 	NULL,
	POSTALCODE	 			character varying(20)	NULL,
	STREET1	 				character varying(250) 	NULL,
	STREET2	 				character varying(250) 	NULL,
	STREET3	 				character varying(250) 	NULL,
	QUALIFICATIONCOMMENTS	character varying(400) 	NULL,
	UOMSET	 				varchar(20) 			NULL,
	UOM	 					varchar(20) 			NULL,
	ESTQUANTITY	 			numeric(15, 4) 			NULL,
	PRODUCTGROUPERPID	 	integer 				NULL,
	PRODUCTGROUP	 		character varying(100) 	NULL,
	PRODUCTSUBGROUPERPID	integer 				NULL,
	PRODUCTSUBGROUP	 		character varying(100) 	NULL,
	BRANDERPID	 			integer 				NULL,
	BRAND	 				character varying(100) 	NULL,
	GRADE	 				character varying(100) 	NULL,
	RAV_APPLICATIONNAME	 	character varying(100) 	NULL,
	MEDICALAPPLICATION	 	varchar(20) 			NULL,
	CONFIDENTIALAPPLICATION	varchar(20) 			NULL,
	MARKET	 				character varying(100) 	NULL,
	SEGMENT	 				character varying(100) 	NULL,
	SUBSEGMENT	 			character varying(100) 	NULL,
	OEM	 					character varying(100) 	NULL,
	APPLDESCRIPTION	 		character varying(200) 	NULL,
	NUMBEROFEMPLOYEES		integer 				NULL,
	PROCESSINGMETHOD		character varying(100) 	NULL,
	NUMBEROFMACHINES		integer 				NULL,
	ESTQUANTITYSI	 		numeric(15, 4)			NULL,
	ESTQUANTITYUS	 		numeric(15, 4) 			NULL,
	OWNER	 				character varying(200) 	NULL,
	OWNERRAVID	 			varchar(10) 			NULL,
	OWNERPERSERPID	 		integer 				NULL,
	CREATEDON	 			timestamp 				NOT NULL,
	CREATEDBY	 			character varying(200) 	NOT NULL,
	CREATEDRAVID	 		varchar(10) 			NULL,
	CREATEDPERSERPID		integer 				NULL,
	MODIFIEDON	 			timestamp 				NOT NULL,
	MODIFIEDBY	 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 		varchar(10) 			NULL,
	MODIFIEDPERSERPID		integer 				NULL,
	MAXCHANGEDDATE	 		timestamp 				NOT NULL
   ,CONSTRAINT CRMLEADS_PK PRIMARY KEY (LEADGUID,SOURCEID)
)
DISTRIBUTE ON (LEADGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_OPPORTUNITIES  
(
	URL	 							varchar(305) 			NULL,
	SOURCEID	 					smallint 				NOT NULL,
	OPPGUID	 						varchar(36) 			NOT NULL,
	OPPNAME	 						character varying(300)	NULL,
	OPPTYPE	 						varchar(20) 			NULL,
	STATUS	 						varchar(20) 			NULL,
	STATUSREASON 					varchar(50) 			NULL,
	EAQ	 							decimal(15, 4) 			NULL,
	UOM	 							varchar(20) 			NULL,
	PRODGROUPERPID	 				integer 				NULL,
	PRODGROUPNAME	 				character varying(100) 	NULL,
	PRODSUBGROUPERPID	 			integer 				NULL,
	PRODSUBGROUPNAME	 			character varying(100) 	NULL,
	BRANDERPID	 					integer 				NULL,
	BRANDNAME	 					character varying(100) 	NULL,
	RMBRAND	 						varchar(10) 			NULL,
	GRADENAME	 					character varying(100) 	NULL,
	APPLICATIONGUID	 				varchar(36) 			NULL,
	APPLICATIONNAME	 				character varying(255) 	NULL,
	OPPDESCRIPTION	 				character varying(1500) 	NULL,
	ACCOUNTGUID						varchar(36) 			NULL,
	ACCOUNTERPID	 				integer 				NULL,
	ACCOUNTNAME	 					character varying(160) 	NULL,
	PRIMARYCONTACTGUID	 			varchar(36) 			NULL,
	PRIMARYCONTACT	 				character varying(160) 	NULL,
	ESTCLOSEDATE	 				date 					NULL,
	MEDICALAPPL	 					varchar(20) 			NULL,
	LOSTTOCOMPETITOR				varchar(20)				NULL, 
	OPPORTUNITYCOMPGUID				varchar(36)				NULL, 
	ACTUALCLOSEDATE					date					NULL, 
	CONFIRMEAQ						decimal(15,4)			NULL, 
	SELLERFAVORITE	 				varchar(20) 			NULL,
	PMFAVORITE	 					varchar(20) 			NULL,
	PRIORITY	 					varchar(20) 			NULL,
	POTENTIALSUCCES	 				varchar(20) 			NULL,
	TRANSACTIONCURR	 				character varying(100) 	NULL,
	PRIMPRODERPID	 				integer 				NULL,
	PRIMPRODNAME	 				character varying(100) 	NULL,
	PRODUCTSEGMENT					varchar(100)			NULL, 
	PRIMPRODBRANDERPID	 			integer 				NULL,
	PRIMPRODBRANDNAME	 			character varying(100) 	NULL,
	PRIMRMBRAND	 					varchar(10) 			NULL,
	PRIMPRODGRADENAME	 			character varying(100) 	NULL,
	PRIMPRODGROUPERPID	 			integer 				NULL,
	PRIMPRODGROUPNAME	 			character varying(100) 	NULL,
	PRIMPRODSUBGROUPERPID	 		integer 				NULL,
	PRIMPRODSUBGROUPNAME	 		character varying(100) 	NULL,
	PRIMPRODCOLORERPID	 			integer 				NULL,
	PRIMPRODCOLORNAME	 			character varying(100) 	NULL,
	PRIMPRODUOMSET	 				character varying(100) 	NULL,
	PRIMPRODMANAGER	 				character varying(200) 	NULL,
	PRIMPRODMANAGERRAVID	 		varchar(10) 			NULL,
	PRIMPRODMANAGERPERSERPID	 	integer 				NULL,
	PRIMPRODCOORDINATER	 			character varying(200) 	NULL,
	PRIMPRODCOORDINATORRAVID	 	varchar(10) 			NULL,
	PRIMPRODCOORDINATORPERSERPID	integer 				NULL,
	SUPPLIERGUID	 				varchar(36) 			NULL,
	PRIMPRODSUPPLIERERPID	 		integer 				NULL,
	PRIMPRODSUPPLIER	 			character varying(160) 	NULL,
	BUSINESSUNIT	 				character varying(160) 	NULL,
	LENERPID	 					integer 				NULL,
	OLEERPID	 					integer 				NULL,
	OLENAME	 						character varying(100) 	NULL,
	OWNER	 						character varying(200) 	NULL,
	OWNERRAVID	 					varchar(10) 			NULL,
	OWNERPERSERPID	 				integer 				NULL,
	CREATEDON	 					timestamp 				NOT NULL,
	CREATEDBY	 					character varying(200) 	NOT NULL,
	CREATEDRAVID	 				varchar(10) 			NULL,
	CREATEDPERSERPID	 			integer 				NULL,
	MODIFIEDON	 					timestamp 				NOT NULL,
	MODIFIEDBY	 					character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 				varchar(10) 			NULL,
	MODIFIEDPERSERPID	 			integer 				NULL,
	UOMSYSTEM	 					character varying(100) 	NULL,
	QUANTITYSI	 					decimal(15, 4) 			NULL,
	QUANTITYUS	 					decimal(15, 4) 			NULL,
	TIMEINDEV	 					numeric(17, 6) 			NULL,
	TIMEINDEVUNIT	 				varchar(8) 				NULL,
	TIMEINPROP	 					decimal(17, 6) 			NULL,
	TIMEINPROPUNIT	 				varchar(8) 				NULL,
	TIMEINSAMP	 					decimal(17, 6) 			NULL,
	TIMEINSAMPUNIT	 				varchar(8) 				NULL,
	TIMEINCLOSE	 					decimal(17, 6) 			NULL,
	TIMEINCLOSEUNIT	 				varchar(8) 				NULL,
	MRFPROCEDURE	 				varchar(20) 			NULL,
	LEADGUID						varchar(36) 			NULL,
	ORIGINATINGLEAD	 				character varying(160) 	NULL,
	PRODUCTUSAGEGUID	 			varchar(36) 			NULL,
	PRODUCTUSAGE	 				character varying(300) 	NULL,
	OURSHAREGUID	 				varchar(36) 			NULL,
	OURSHARE	 					character varying(300) 	NULL,
	COMPETITORSHAREGUID	 			varchar(36) 			NULL,
	COMPETITORSHARE	 				character varying(300) 	NULL,
	PIPELINEPHASE	 				character varying(200) 	NULL,
	RPCLENTITY	 					character varying(128) 	NULL,
	MAXCHANGEDDATE	 				timestamp 			NOT NULL	
	
	,CONSTRAINT CRMOPPORTUNITIES_PK PRIMARY KEY (OPPGUID,SOURCEID)
)
DISTRIBUTE ON (OPPGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_OPPORTUNITYCOMPETITORS  
(
	SOURCEID	 					smallint 				NOT NULL,
	COMPETITORGUID					varchar(36)				NULL,
	OPPORTUNITYCOMPGUID				varchar(36) 			NOT NULL,
	OPPORTUNITYGUID					varchar(36)				NULL, 
	STATUS	 						varchar(20) 			NULL,
	STATUSREASON 					varchar(50) 			NULL,
	BRANDERPID						integer					NULL, 
	BRANDNAME						varchar(100)			NULL, 
	GRADENAME						varchar(100)			NULL,
	BUSINESSUNIT					varchar(160)			NULL, 
	OPPCOMPCOMMENT					varchar(500)			NULL, 
	VOLUME							decimal(15,4)			NULL, 
	CREATEDON	 					timestamp 				NOT NULL,
	CREATEDBY	 					character varying(200) 	NOT NULL,
	CREATEDRAVID	 				varchar(10) 			NULL,
	CREATEDPERSERPID	 			integer 				NULL,
	MODIFIEDON	 					timestamp 				NOT NULL,
	MODIFIEDBY	 					character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 				varchar(10) 			NULL,
	MODIFIEDPERSERPID	 			integer 				NULL,
	MAXCHANGEDDATE	 				timestamp 				NOT NULL	
	,CONSTRAINT CRMOPPORTUNITIES_PK PRIMARY KEY (OPPORTUNITYCOMPGUID,SOURCEID)
)
DISTRIBUTE ON (OPPORTUNITYCOMPGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_OPPORTUNITYPRODUCTS 
(
	URL	 					varchar(312) 			NULL,
	SOURCEID	 			smallint 				NOT NULL,
	OPPPRODUCTGUID	 		varchar(36) 			NOT NULL,
	OPPPRODUCTNAME	 		character varying(500)	NULL,
	PRODUCTSEGMENT			varchar(100)			NULL, 
	OPPORTUNITYGUID	 		varchar(36) 			NULL,
	BUSINESSUNIT	 		character varying(160) 	NULL,
	LENERPID	 			integer 				NULL,
	OLEERPID	 			integer 				NULL,
	OLENAME	 				character varying(100) 	NULL,
	WRITEIN	 				varchar(30) 			NULL,
	OPPPRODUCTERPID	 		integer 				NULL,
	EXISTINGPRODUCTNAME		character varying(100) 	NULL,
	SUPPLIERGUID	 		varchar(36) 			NULL,
	SUPPLIERID	 			integer 				NULL,
	SUPPLIERNAME	 		character varying(160) 	NULL,
	QUANTITY	 			numeric(15, 4) 			NULL,
	UOM	 					varchar(20) 			NULL,
	PRICEPERUNIT	 		numeric(25, 10) 		NULL,
	CURRENCY	 			character varying(100) 	NULL,
	ISPRIMARY	 			character varying(20) 	NULL,
	OWNER	 				character varying(200) 	NULL,
	OWNERRAVID	 			varchar(10) 			NULL,
	OWNERPERSERPID	 		integer 				NULL,
	CREATEDON	 			timestamp 				NOT NULL,
	CREATEDBY	 			character varying(200) 	NOT NULL,
	CREATEDRAVID	 		varchar(10) 			NULL,
	CREATEDPERSERPID	 	integer 				NULL,
	MODIFIEDON	 			timestamp 				NOT NULL,
	MODIFIEDBY	 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID	 		varchar(10) 			NULL,
	MODIFIEDPERSERPID	 	integer 				NULL,
	MAXCHANGEDDATE	 		timestamp 				NOT NULL
	,CONSTRAINT CRMOPPORTUNITYPRODUCTS_PK PRIMARY KEY (OPPPRODUCTGUID,SOURCEID)
)
DISTRIBUTE ON (OPPPRODUCTGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_PHONECALLS
(
	URL 				varchar(303) 			NULL,
	SOURCEID 			smallint 				NOT NULL,
	ACTIVITYGUID 		varchar(36) 			NOT NULL,
	ACTIVITYTYPE 		varchar(20) 			NULL,
	REGARDINGENTITYGUID varchar(36) 			NULL,
	REGARDINGENTITY 	character varying(128)	NOT NULL,
	REGARDING 			character varying(300)	NULL,
	BUSINESSUNIT 		character varying(160) 	NULL,
	STATUS				varchar(20) 			NULL,
	STATUSREASON		varchar(20) 			NULL,
	DIRECTION 			varchar(20) 			NULL,
	PRIORITY 			varchar(20) 			NULL,
	SUBJECT 			character varying(200) 	NULL,
	DESCRIPTION 		character varying(2000) 	NULL,
	CALLFROM 			character varying(400) 	NULL,
	CALLTO 				character varying(300) NULL,
	SCHEDULEDSTART 		timestamp 				NULL,
	SCHEDULEDDURATION 	integer 				NULL,
	SCHEDULEDEND 		timestamp 				NULL,
	ACTUALSTART 		timestamp 				NULL,
	ACTUALDURATION 		integer 				NULL,
	ACTUALEND 			timestamp 				NULL,
	ACTIVITYREPORTGUID	varchar(36) 			NULL,
	ACTIVITYREPORT 		character varying(250) 	NULL,
	OWNER 				character varying(200) 	NULL,
	OWNERRAVID 			varchar(10) 			NULL,
	OWNERPERSERPID 		integer 				NULL,
	CREATEDON 			timestamp 				NOT NULL,
	CREATEDBY 			character varying(200) 	NOT NULL,
	CREATEDRAVID 		varchar(10) 			NULL,
	CREATEDPERSERPID 	integer 				NULL,
	MODIFIEDON 			timestamp 				NOT NULL,
	MODIFIEDBY 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID 		varchar(10) 			NULL,
	MODIFIEDPERSERPID 	integer 				NULL,
	MAXCHANGEDDATE 		timestamp 				NOT NULL
	,CONSTRAINT CRMPHONECALLS_PK PRIMARY KEY (ACTIVITYGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_PRODUCTUSAGES
(
	URL 					varchar(312) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	PRODUCTUSAGEGUID 		varchar(36) 			NOT NULL,
	PRODUCTUSAGE 			character varying(300) 	NULL,
	STATUS					varchar(20)				NULL, 
	STATUSREASON			varchar(20)				NULL, 
	ACCOUNTGUID 			varchar(36) 			NULL,
	ACCOUNTERPID 			integer 				NULL,
	ACCOUNTNAME 			character varying(160) 	NULL,
	BUSINESSUNIT 			character varying(160) 	NULL,
	LENERPID 				integer 				NULL,
	OLEERPID 				integer 				NULL,
	OLENAME 				character varying(100) 	NULL,
	DATAQUALITYRATING 		integer 				NULL,
	CONTACTGUID 			varchar(36) 			NULL,
	FULLNAME 				character varying(160) 	NULL,
	PRODUCTINPORTFOLIO 		varchar(10) 			NULL,
	PRODUCT 				character varying(100) 	NULL,
	PRODUCTSEGMENT			varchar(100)			NULL, 
	PRODGROUPERPID 			integer 				NULL,
	PRODGROUP 				character varying(100) 	NULL,
	PRODSUBGROUPERPID 		integer 				NULL,
	PRODSUBGROUP 			character varying(100) 	NULL,
	POTENTIALCATEGORY 		varchar(50) 			NULL,
	ENDSON 					date 					NULL,
	GRADE 					character varying(100) 	NULL,
	BRANDERPID 				integer 				NULL,
	BRAND 					character varying(100) 	NULL,
	RMBRAND 				varchar(10) 			NULL,
	PRODUCERSUPPLIER 		character varying(160) 	NULL,
	PRODUCERCOLORCODE 		character varying(100) 	NULL,
	COLORERPID 				integer 				NULL,
	COLOR 					character varying(100) 	NULL,
	PRODUCTERPID 			integer 				NULL,
	UOM 					varchar(20) 			NULL,
	TOTALEAQ 				decimal(15, 4) 			NULL,
	OURSHAREEAQ 			decimal(15, 4) 			NULL,
	COMPETITORSHAREEAQ 		decimal(15, 4) 			NULL,
	BUDGET 					decimal(15, 4) 			NULL,
	YTDBUDGET 				decimal(15, 4) 			NULL,
	YTD 					decimal(15, 4) 			NULL,
	LASTORDERDATE 			date 					NULL,
	COMPETITORSHARES 		varchar(20) 			NULL,
	COMPETITORGUID 			varchar(36) 			NULL,
	PRIMARYCOMPETITORERPID	integer 				NULL,
	PRIMARYCOMPETITOR 		character varying(100) 	NULL,
	UOMSYSTEMERPID 			integer 				NULL,
	UOMSYSTEM 				varchar(20) 			NULL,
	UOMNAME 				varchar(20) 			NULL,
	UOMSET 					varchar(20) 			NULL,
	TOTALEAQSI 				decimal(15, 4) 			NULL,
	TOTALEAQUS 				decimal(15, 4) 			NULL,
	OURSHAREEAQSI 			decimal(15, 4) 			NULL,
	OURSHAREEAQUS 			decimal(15, 4) 			NULL,
	COMPETITORSHAREEAQSI 	decimal(15, 4) 			NULL,
	COMPETITORSHAREEAQUS 	decimal(15, 4) 			NULL,
	BUDGETSI 				decimal(15, 4) 			NULL,
	BUDGETUS 				decimal(15, 4) 			NULL,
	YTDBUDGETSI 			decimal(15, 4) 			NULL,
	YTDBUDGETUS 			decimal(15, 4) 			NULL,
	YTDSI 					decimal(15, 4) 			NULL,
	YTDUS 					decimal(15, 4) 			NULL,
	CURRENCY 				character varying(80) 	NULL,
	LEADGUID 				varchar(36) 			NULL,
	ORIGINATINGLEAD 		character varying(160) 	NULL,
	OPPORTUNITYGUID 		varchar(36) 			NULL,
	ORIGINATINGOPPORTUNITY 	character varying(300) 	NULL,
	QUOTEGUID 				varchar(36) 			NULL,
	ORIGINATINGQUOTE 		character varying(300) 	NULL,
	APPLICATIONGUID 		varchar(36) 			NULL,
	ORIGINATINGAPPLICATION 	character varying(255) 	NULL,
	ORDERHISTORYGUID 		varchar(36) 			NULL,
	CURRENTYEARORDERHISTORY	character varying(100) 	NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	CREATEDON 				timestamp 				NOT NULL,
	CREATEDBY 				character varying(200) 	NOT NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NOT NULL,
	MODIFIEDBY 				character varying(200) 	NOT NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL
	,CONSTRAINT CRMPRODUCTUSAGES_PK PRIMARY KEY (PRODUCTUSAGEGUID,SOURCEID)
)
DISTRIBUTE ON (PRODUCTUSAGEGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_QUOTEDETAILS
(
	URL 					varchar(305) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	QUOTEDETAILGUID 		varchar(36) 			NOT NULL,
	QUOTEDETAILNAME 		character varying(500) 	NULL,
	QUOTEGUID 				varchar(36) 			NULL,
	QUOTENAME 				character varying(300) 	NULL,
	ACCOUNTGUID 			varchar(36) 			NULL,
	ACCOUNTERPID 			integer 				NULL,
	ACCOUNTNAME 			character varying(160) 	NULL,
	PRODUCTUSAGE 			character varying(300) 	NULL,
	BUSINESSUNIT 			character varying(160) 	NULL,
	LENERPID 				integer 				NULL,
	OLEERPID 				integer 				NULL,
	OLENAME 				character varying(100) 	NULL,
	PRODUCTERPID 			integer 				NULL,
	PRODUCTNAME 			character varying(100) 	NULL,
	PRODUCTSEGMENT			varchar(100)			NULL, 
	PACAKAGING 				character varying(100) 	NULL,
	QUANTITY 				decimal(15, 4) 			NULL,
	QUANTITYSI 				decimal(15, 4) 			NULL,
	QUANTITYUS 				decimal(15, 4) 			NULL,
	UOM 					varchar(20) 			NULL,
	PRICEPERUNIT 			decimal(25, 10) 		NULL,
	PRICEPERUNITSI 			decimal(25, 10) 		NULL,
	PRICEPERUNITUS 			decimal(25, 10) 		NULL,
	CURRENCY 				character varying(100) 	NULL,
	ADDITIONALINFO 			character varying(1000) 	NULL,
	NUMBEROFORDERREQUESTS	integer 				NULL,
	ROLLUPLASTUPDATED 		timestamp 				NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	CREATEDON 				timestamp 				NOT NULL,
	CREATEDBY 				character varying(200) 	NOT NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NOT NULL,
	MODIFIEDBY 				character varying(200)	NOT NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL
	,CONSTRAINT CRMQUOTEDETAILS_PK PRIMARY KEY (QUOTEDETAILGUID,SOURCEID)
)
DISTRIBUTE ON (QUOTEDETAILGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_QUOTES
(
	URL 					varchar(299) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	QUOTEGUID 				varchar(36)  			NOT NULL,
	QUOTENAME 				character varying(300)	NULL,
	ACCOUNTGUID 			varchar(36)  			NULL,
	ACCOUNTERPID 			integer 				NULL,
	ACCOUNTNAME 			character varying(160) 	NULL,
	BUSINESSUNIT 			character varying(160) 	NULL,
	LENERPID 				integer 				NULL,
	OLEERPID 				integer 				NULL,
	OLENAME 				character varying(100) 	NULL,
	STATUS	 				varchar(20) 			NULL,
	STATUSREASON			varchar(100) 			NULL,
	REVISIONNUMBER 			integer 				NULL,
	EFFECTIVEFROM 			date 					NULL,
	EFFICTIVETO 			date 					NULL,
	SHIPPINGERPID 			integer 				NULL,
	SHIPPINGADDRESS 		character varying(200) 	NULL,
	BILLINGADDRESSERPID 	integer 				NULL,
	BILLINGADDRESS 			character varying(200) 	NULL,
	WAREHOUSEADDRESSERPID 	integer 				NULL,
	WAREHOUSEADDRESS 		character varying(100) 	NULL,
	INCOTERMERPID 			integer 				NULL,
	INCOTERM 				varchar(20) 			NULL,
	DESCRIPTION 			character varying(1500) 	NULL,
	UOMSYSERPID 			integer 				NULL,
	UOMSYSTEM 				varchar(20) 			NULL,
	CURRENCY 				character varying(100) 	NULL,
	PRIMARYCONTACTGUID 		varchar(36)  			NULL,
	PRIMARYCONTACT 			character varying(160) 	NULL,
	SALESPERSON 			character varying(200) 	NULL,
	SALESPERSONRAVID 		varchar(10) 			NULL,
	SALESPERSERPID 			integer 				NULL,
	FOLLUWUP 				varchar(30) 			NULL,
	FOLLOWUPSTATUS 			varchar(30) 			NULL,
	LASTQUOTEGENERATEDBY	character varying(200) 	NULL,
	LASTQUOTEBYRAVID 		character varying(100) 	NULL,
	LASTQUOTEBYERPID 		integer 				NULL,
	LASTQUOTEGENERATEDON 	timestamp 				NULL,
	LASTQUOTETEMPLATE 		character varying(100) 	NULL,
	PAYMENTCONDITION1 		character varying(100) 	NULL,
	DISCOUNTPERCENTAGE1 	decimal(31, 2) 			NULL,
	PAYMENTCONDITION2 		character varying(100) 	NULL,
	DISCOUNTPERCENTAGE2 	decimal(31, 2) 			NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	CREATEDON 				timestamp 				NOT NULL,
	CREATEDBY 				character varying(200) 	NOT NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NOT NULL,
	MODIFIEDBY 				character varying(200) 	NOT NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL
	,CONSTRAINT CRMQUOTES_PK PRIMARY KEY (QUOTEGUID,SOURCEID)
)
DISTRIBUTE ON (QUOTEGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_RPCL
(
	URL 					varchar(302)	 		NULL,
	SOURCEID 				smallint 				NOT NULL,
	RPCLGUID 				varchar(36) 			NOT NULL,
	RPCLNAME 				character varying(100)	NULL,
	ACCOUNTGUID 			varchar(36) 			NULL,
	ACCOUNTERPID 			character varying(100) 	NULL,
	ACCOUNTNAME				character varying(160) 	NULL,
	OPPGUID 				varchar(36) 			NULL,
	OPPNAME 				character varying(300) 	NULL,
	STATUS					varchar(20) 			NULL,
	STATUSREASON 			varchar(50) 			NULL,
	CENTURIONNAME 			character varying(200) 	NULL,
	CENTURIONRAVID 			varchar(10) 			NULL,
	CENTURIONPERSERPID 		integer 				NULL,
	CUSTPRICEINDICATION 	decimal(31, 4) 			NULL,
	TRANSACTIONCURR 		character varying(100) 	NULL,
	COMPETITORMATERIAL 		character varying(100) 	NULL,
	MANUFSTARTDATE 			timestamp 				NULL,
	MANUFCUSTOMERSEGMENT 	character varying(350) 	NULL,
	KEYAPPLREQUIREMENTS 	character varying(1000) 	NULL,
	PRIME 					character varying(350) 	NULL,
	PREUSE 					character varying(350) 	NULL,
	POSTUSE 				character varying(350) 	NULL,
	FILLERTYPE 				character varying(350) 	NULL,
	FILLERCONTENTPERC 		integer 				NULL,
	COLOR 					character varying(100) 	NULL,
	UVSTABILIZATION 		character varying(350) 	NULL,
	ULCARD 					character varying(350) 	NULL,
	HALOGENFREE 			character varying(350) 	NULL,
	FLAMMABLE 				character varying(350) 	NULL,
	KEYMATERIALREQUIREMENTS	character varying(1000) 	NULL,
	UOM 					varchar(20) 			NULL,
	EAQ 					decimal(15, 4) 			NULL,
	CURRENCY 				character varying(100) 	NULL,
	REQUESTEDGROUP 			character varying(100) 	NULL,
	REQUESTEDSUBGROUP 		character varying(100) 	NULL,
	REQUESTEDBRAND 			character varying(100) 	NULL,
	REQUESTEDGRADE 			character varying(100) 	NULL,
	APPLICATIONGUID 		character varying(36) 	NULL,
	APPLICATION 			character varying(255) 	NULL,
	ESTCLOSEDATE 			date 					NULL,
	INVESTIGATIONOUTCOME 	character varying(350) 	NULL,
	INVESTIGATEDBY 			character varying(200) 	NULL,
	INVESTBYRAVID 			varchar(10) 			NULL,
	INVESTBYPERSERPID 		integer 				NULL,
	INVESTIGATEDON 			timestamp 				NULL,
	CLOSEDATE 				timestamp 				NULL,
	CLOSEDESCRIPTION 		character varying(200) 	NULL,
	RPCLSTATUSREASONCODE 	character varying(350) 	NULL,
	BUSINESSUNIT 			character varying(160) 	NULL,
	LENERPID 				integer 				NULL,
	OLEERPID 				integer 				NULL,
	OLENAME 				character varying(100) 	NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	CREATEDON 				timestamp 				NULL,
	CREATEDBY 				character varying(200) 	NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NULL,
	MODIFIEDBY 				character varying(200) 	NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL
	,CONSTRAINT CRMRPCL_PK PRIMARY KEY (RPCLGUID,SOURCEID)
)
DISTRIBUTE ON (RPCLGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_SALESTEAMMEMBERS 
(
	URL					varchar(313)			NULL,
	SOURCEID 			smallint 				NOT NULL,
	SALESTEAMMEMBERGUID varchar(36)				NOT NULL,
	ACCOUNTGUID 		varchar(36) 			NOT NULL,
	ACCOUNTNAME 		character varying(160) 	NULL,
	ACCOUNTERPID 		character varying(100) 	NULL,
	BUSINESSUNIT 		character varying(160) 	NULL,
	SALESROLE 			character varying(100) 	NULL,
	TEAMMEMBER 			character varying(100)	NOT NULL,
	STATUS 				varchar(20) 			NULL,
	STATUSREASON		varchar(20) 			NULL,
	OWNER 				character varying(200) 	NULL,
	OWNERRAVID 			varchar(10) 			NULL,
	OWNERPERSERPID 		integer 				NULL,
	CREATEDON 			timestamp 				NOT NULL,
	CREATEDBY 			character varying(200) 	NOT NULL,
	CREATEDRAVID 		varchar(10) 			NULL,
	CREATEDPERSERPID	integer 				NULL,
	MODIFIEDON 			timestamp 				NOT NULL,
	MODIFIEDBY 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID 		varchar(10) 			NULL,
	MODIFIEDPERSERPID 	integer 				NULL,
	MAXCHANGEDDATE 		timestamp 				NOT NULL
	,CONSTRAINT CRMSALESTEAMMEMBERS_PK PRIMARY KEY (SALESTEAMMEMBERGUID,SOURCEID)
)
DISTRIBUTE ON (SALESTEAMMEMBERGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_SAMPLES 
(
	URL 						varchar(309) 			NULL,
	SOURCEID 					smallint 				NOT NULL,
	SAMPLEGUID 					varchar(36) 			NOT NULL,
	SAMPLENAME 					character varying(100)	NULL,
	ACCOUNTGUID 				varchar(36) 			NULL,
	ACCOUNTERPID 				integer 				NULL,
	ACCOUNTNAME 				character varying(160) 	NULL,
	PRODUCTNAME 				character varying(100) 	NULL,
	PRODUCTSEGMENT				varchar(100)			NULL, 
	STATUS		 				varchar(20) 			NULL,
	STATUSREASON				varchar(30)				NULL, 
	OPPORTUNITYGUID 			varchar(36) 			NULL,
	OPPORTUNITYNAME 			character varying(300) 	NULL,
	PRODUCTUSAGEGUID 			varchar(36) 			NULL,
	PRODUCTUSAGE 				character varying(300) 	NULL,
	BUSINESSUNIT 				character varying(160) 	NULL,
	LENERPID 					integer 				NULL,
	OLEERPID 					integer 				NULL,
	OLENAME 					character varying(100) 	NULL,
	WRITEIN 					varchar(20) 			NULL,
	OPPORTUNITYPRODUCT 			character varying(500) 	NULL,
	QUANTITY 					decimal(15, 4) 			NULL,
	COMMENT 					character varying(500) 	NULL,
	PRODUCTMANAGER 				character varying(200) 	NULL,
	PRODUCTMANAGERRAVID 		varchar(10) 			NULL,
	PRODUCTMANAGERPERSERPID		integer 				NULL,
	PRODUCTCOORDINATOR 			character varying(200) 	NULL,
	PRODCOORDINATORRAVID 		varchar(10) 			NULL,
	PRODCOORDINATORPERSERPID	integer 				NULL,
	CSR 						character varying(200) 	NULL,
	CSRRAVID 					varchar(10) 			NULL,
	CSRPERSERPID 				integer 				NULL,
	REQUESTEDDELIVERYON 		timestamp 				NULL,
	INCOTERMERPID 				integer 				NULL,
	INCOTERM 					varchar(20) 			NULL,
	SHIPPINGADDERPID 			integer 				NULL,
	SHIPPINGADDRESS 			character varying(200) 	NULL,
	BILLINGADDRERPID			integer 				NULL,
	BILLINGADDRESS 				character varying(200) 	NULL,
	REVIEWEDBY 					character varying(200) 	NULL,
	REVIEWEDRAVID 				varchar(10) 			NULL,
	REVIEWEDPERSERPID 			integer 				NULL,
	REVIEWEDON 					timestamp 				NULL,
	REVIEWOUTCOME 				varchar(50) 			NULL,
	MOTIVATION 					character varying(500) 	NULL,
	CUSTOMERAPPROVAL 			varchar(30) 			NULL,
	FEEDBACKCOMMENT 			character varying(1000) 	NULL,
	CONFIRMEDDELIVERYDATE 		date 					NULL,
	ORDERNUMBER 				character varying(100) 	NULL,
	OHMSTATUS 					varchar(30) 			NULL,
	PRODUCT 					character varying(100) 	NULL,
	WRITEINPRODUCT 				varchar(20) 			NULL,
	PRODUCTERPID 				integer 				NULL,
	CUSTOMERERPID 				integer 				NULL,
	PRICEPERUNIT 				decimal(25, 10) 		NULL,
	CURRENCY 					character varying(100) 	NULL,
	FREIGHTAMOUNT 				decimal(15, 4) 			NULL,
	EAQSI 						decimal(15, 4) 			NULL,
	EAQUS 						decimal(15, 4) 			NULL,
	UOMSYSTEMERPID 				integer 				NULL,
	UOMSYSTEM 					varchar(20) 			NULL,
	UOM 						varchar(20) 			NULL,
	CREATEDON 					timestamp 				NOT NULL,
	CREATEDBY 					character varying(200) 	NOT NULL,
	CREATEDRAVID 				varchar(10) 			NULL,
	CREATEDPERSERPID 			integer 				NULL,
	MODIFIEDON 					timestamp 				NOT NULL,
	MODIFIEDBY 					character varying(200) 	NOT NULL,
	MODIFIEDRAVID 				varchar(10) 			NULL,
	MODIFIEDPERSERPID 			integer 				NULL,
	CREATEDINOHMON 				date 					NULL,
	OWNER 						character varying(200) 	NULL,
	OWNERRAVID 					varchar(10) 			NULL,
	OWNERPERSERPID 				integer 				NULL,
	FOLLOWUPMODE 				varchar(100) 			NULL,
	FOLLOWUPSTATUS 				varchar(100) 			NULL,
	MAXCHANGEDDATE 				timestamp 				NOT NULL
	,CONSTRAINT CRMSAMPLES_PK PRIMARY KEY (SAMPLEGUID,SOURCEID)
)
DISTRIBUTE ON (SAMPLEGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_SOURCE 
(
	ID 			smallint 		NOT NULL,
	ENVIRONMENT varchar(100) 	NULL,
	SOURCEID 	smallint 		NULL,
	SOURCE 		varchar(10) 	NULL,
	CREATEDBY 	varchar(30) 	NOT NULL,
	CREATEDON 	date 			NOT NULL,
	MODIFIEDBY 	varchar(30) 	NOT NULL,
	MODIFIEDON 	date 			NOT NULL
	,CONSTRAINT CRMSOURCE_PK PRIMARY KEY (ID)
)
DISTRIBUTE ON (ID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_TASKS
(
	URL 				varchar(298) 			NULL,
	SOURCEID 			smallint 				NOT NULL,
	ACTIVITYGUID 		varchar(36)  			NOT NULL,
	ACTIVITYTYPE 		varchar(20) 			NULL,
	REGARDINGENTITYGUID varchar(36)  			NULL,
	REGARDINGENTITY 	character varying(128) 	NULL,
	REGARDING 			character varying(300) 	NULL,
	REGARDINGACCOUNT 	character varying(160) 	NULL,
	BUSINESSUNIT 		character varying(160) 	NULL,
	STATUS				varchar(20) 			NULL,
	STATUSREASON		varchar(20) 			NULL,
	PRIORITY 			varchar(20) 			NULL,
	SUBJECT 			character varying(200) 	NULL,
	DESCRIPTION 		character varying(2000) 	NULL,
	SCHEDULEDSTART 		timestamp 				NULL,
	SCHEDULEDDURATION 	integer 				NULL,
	SCHEDULEDEND 		timestamp 				NULL,
	ACTUALSTART 		timestamp 				NULL,
	ACTUALDURATION 		integer 				NULL,
	ACTUALEND 			timestamp 				NULL,
	ACTIVITYREPORTGUID	varchar(36) 			NULL,
	ACTIVITYREPORT 		character varying(250) 	NULL,
	OWNER 				character varying(200) 	NULL,
	OWNERRAVID 			varchar(10) 			NULL,
	OWNERPERSERPID 		integer 				NULL,
	CREATEDON 			timestamp 				NOT NULL,
	CREATEDBY 			character varying(200) 	NOT NULL,
	CREATEDRAVID 		varchar(10) 			NULL,
	CREATEDPERSERPID 	integer 				NULL,
	MODIFIEDON 			timestamp 				NOT NULL,
	MODIFIEDBY 			character varying(200) 	NOT NULL,
	MODIFIEDRAVID 		varchar(10) 			NULL,
	MODIFIEDPERSERPID 	integer 				NULL,
	MAXCHANGEDDATE 		timestamp 				NOT NULL
	,CONSTRAINT CRMTASKS_PK PRIMARY KEY (ACTIVITYGUID,SOURCEID)
)
DISTRIBUTE ON (ACTIVITYGUID,SOURCEID)
;

CREATE TABLE GAUSS_BIGD.MSCRM_USAGEDETAILS 
(
	URL 					varchar(323) 			NULL,
	SOURCEID 				smallint 				NOT NULL,
	USAGEDETAILGUID 		varchar(36) 			NOT NULL,
	STATUS					varchar(20)				NULL, 
	STATUSREASON			varchar(20)				NULL, 
	USAGEDETAILNAME 		character varying(300)	NULL,
	ACCOUNTGUID 			varchar(36) 			NULL,
	ACCOUNTERPID 			integer 				NULL,
	ACCOUNT 				character varying(160) 	NULL,
	PRODUCTUSAGEGUID 		varchar(36) 			NULL,
	PRODUCTUSAGE 			character varying(300) 	NULL,
	COMPETITORSHARES 		varchar(20) 			NULL,
	APPLICATIONGUID 		varchar(36) 			NULL,
	APPLICATIONNAME 		character varying(255) 	NULL,
	MRFPROCEDURE 			varchar(20) 			NULL,
	OPPORTUNITYGUID 		varchar(36) 			NULL,
	LATESTSHARESHIFTATTEMPT	character varying(300) 	NULL,
	APPLICATIONSUMMARY 		character varying(1000) 	NULL,
	SHARETYPE 				varchar(30) 			NULL,
	EAQ 					decimal(15, 4) 			NULL,
	COMPETITORGUID 			varchar(36) 			NULL,
	SUPPLIERERPID 			integer 				NULL,
	SUPPLIEDBY 				character varying(100) 	NULL,
	BRANDERPID 				integer 				NULL,
	BRAND 					character varying(100) 	NULL,
	GRADE 					character varying(100) 	NULL,
	COMMENT 				character varying(32000) 	NULL,
	UOMSYSTEMERPID 			integer 				NULL,
	UOMSYSTEM 				varchar(20) 			NULL,
	UOM 					varchar(20) 			NULL,
	EAQSI 					decimal(15, 4) 			NULL,
	EAQUS 					decimal(15, 4) 			NULL,
	CREATEDBY 				character varying(200) 	NOT NULL,
	CREATEDRAVID 			varchar(10) 			NULL,
	CREATEDPERSERPID 		integer 				NULL,
	CREATEDON 				timestamp 				NOT NULL,
	MODIFIEDBY 				character varying(200) 	NOT NULL,
	MODIFIEDRAVID 			varchar(10) 			NULL,
	MODIFIEDPERSERPID 		integer 				NULL,
	MODIFIEDON 				timestamp 				NOT NULL,
	OWNER 					character varying(200) 	NULL,
	OWNERRAVID 				varchar(10) 			NULL,
	OWNERPERSERPID 			integer 				NULL,
	MAXCHANGEDDATE 			timestamp 				NOT NULL
	, CONSTRAINT CRMUSAGEDETAILS_PK PRIMARY KEY (USAGEDETAILGUID,SOURCEID) 
)
DISTRIBUTE ON (USAGEDETAILGUID,SOURCEID)
;
