MERGE
INTO
	GAUSS_BIGD.MSCRM_ACCOUNTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_ACCOUNTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_ACCOUNTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.accountguid = tgt.ACCOUNTGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.CHANNEL = src.CHANNEL,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.BUYINGSTATUS = src.BUYINGSTATUS,tgt.ACCOUNTTYPEDESC = src.ACCOUNTTYPEDESC,tgt.PROSPECTVALIDATIONSTATUS = src.PROSPECTVALIDATIONSTATUS,tgt.SEGMENT = src.SEGMENT,tgt.FISCALACCOUNTGUID = src.FISCALACCOUNTGUID,tgt.PRIMARYCONTACT = src.PRIMARYCONTACT,tgt.LEGALADDRESSERPID = src.LEGALADDRESSERPID,tgt.LEGALADDRESS = src.LEGALADDRESS,tgt.PRIMARYADDRESSERPID = src.PRIMARYADDRESSERPID,tgt.PRIMARYADDRESS = src.PRIMARYADDRESS,tgt.ADDRESSLINE1 = src.ADDRESSLINE1,tgt.ADDRESSLINE2 = src.ADDRESSLINE2,tgt.POSTALCODE = src.POSTALCODE,tgt.CITY = src.CITY,tgt.PROVINCE = src.PROVINCE,tgt.COUNTY = src.COUNTY,tgt.COUNTRY = src.COUNTRY,tgt.TERRITORYERPID = src.TERRITORYERPID,tgt.TERRITORY = src.TERRITORY,tgt.PHONE = src.PHONE,tgt.FAX = src.FAX,tgt.EMAIL = src.EMAIL,tgt.WEBSITEURL = src.WEBSITEURL,tgt.LANGUAGEERPID = src.LANGUAGEERPID,tgt.LANGUAGE = src.LANGUAGE,tgt.NUMBEROFEMP = src.NUMBEROFEMP,tgt.NUMBEROFMACH = src.NUMBEROFMACH,tgt.COMPANYCOMMENT = src.COMPANYCOMMENT,tgt.UOMERPID = src.UOMERPID,tgt.UOMNAME = src.UOMNAME,tgt.PREFERREDCURR = src.PREFERREDCURR,tgt.TRANSACTIONCURR = src.TRANSACTIONCURR,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE,tgt.SALESPERSON = src.SALESPERSON,tgt.SALESPERSONRAVID = src.SALESPERSONRAVID,tgt.SALESPERSONERPID = src.SALESPERSONERPID,tgt.CSR = src.CSR,tgt.CSRRAVID = src.CSRRAVID,tgt.CSRERPID = src.CSRERPID	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,CHANNEL,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,STATUS,STATUSREASON,BUYINGSTATUS,ACCOUNTTYPEDESC,PROSPECTVALIDATIONSTATUS,SEGMENT,FISCALACCOUNTGUID,PRIMARYCONTACT,LEGALADDRESSERPID,LEGALADDRESS,PRIMARYADDRESSERPID,PRIMARYADDRESS,ADDRESSLINE1,ADDRESSLINE2,POSTALCODE,CITY,PROVINCE,COUNTY,COUNTRY,TERRITORYERPID,TERRITORY,PHONE,FAX,EMAIL,WEBSITEURL,LANGUAGEERPID,LANGUAGE,NUMBEROFEMP,NUMBEROFMACH,COMPANYCOMMENT,UOMERPID,UOMNAME,PREFERREDCURR,TRANSACTIONCURR,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE,SALESPERSON,SALESPERSONRAVID,SALESPERSONERPID,CSR,CSRRAVID,CSRERPID) 
VALUES 
(src.URL,src.SOURCEID,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.CHANNEL,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.STATUS,src.STATUSREASON,src.BUYINGSTATUS,src.ACCOUNTTYPEDESC,src.PROSPECTVALIDATIONSTATUS,src.SEGMENT,src.FISCALACCOUNTGUID,src.PRIMARYCONTACT,src.LEGALADDRESSERPID,src.LEGALADDRESS,src.PRIMARYADDRESSERPID,src.PRIMARYADDRESS,src.ADDRESSLINE1,src.ADDRESSLINE2,src.POSTALCODE,src.CITY,src.PROVINCE,src.COUNTY,src.COUNTRY,src.TERRITORYERPID,src.TERRITORY,src.PHONE,src.FAX,src.EMAIL,src.WEBSITEURL,src.LANGUAGEERPID,src.LANGUAGE,src.NUMBEROFEMP,src.NUMBEROFMACH,src.COMPANYCOMMENT,src.UOMERPID,src.UOMNAME,src.PREFERREDCURR,src.TRANSACTIONCURR,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE,src.SALESPERSON,src.SALESPERSONRAVID,src.SALESPERSONERPID,src.CSR,src.CSRRAVID,src.CSRERPID);

MERGE
INTO
	GAUSS_BIGD.MSCRM_ACTIVITYREPORTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_ACTIVITYREPORTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_ACTIVITYREPORTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ActivityReportGuid = tgt.ActivityReportGuid
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYREPORTGUID = src.ACTIVITYREPORTGUID,tgt.ACTIVITYREPORT = src.ACTIVITYREPORT,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNT = src.ACCOUNT,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.CUSTOMERCONNECTION = src.CUSTOMERCONNECTION,tgt.OBJECTIVES = src.OBJECTIVES,tgt.MAINFINDINGS = src.MAINFINDINGS,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDINGGUID = src.REGARDINGGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ORIGINATINGOPPORTUNITYGUID = src.ORIGINATINGOPPORTUNITYGUID,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYREPORTGUID,ACTIVITYREPORT,ACCOUNTGUID,ACCOUNTERPID,ACCOUNT,BUSINESSUNIT,STATUS,STATUSREASON,CUSTOMERCONNECTION,OBJECTIVES,MAINFINDINGS,REGARDINGENTITY,REGARDINGGUID,ACTIVITYTYPE,ACTIVITYGUID,ORIGINATINGOPPORTUNITYGUID,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYREPORTGUID,src.ACTIVITYREPORT,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNT,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.CUSTOMERCONNECTION,src.OBJECTIVES,src.MAINFINDINGS,src.REGARDINGENTITY,src.REGARDINGGUID,src.ACTIVITYTYPE,src.ACTIVITYGUID,src.ORIGINATINGOPPORTUNITYGUID,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_APPLICATIONS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_APPLICATIONS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_APPLICATIONS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ApplicationGuid = tgt.ApplicationGuid
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.APPLICATIONGUID = src.APPLICATIONGUID,tgt.APPLICATIONNAME = src.APPLICATIONNAME,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.LOCALLANGUAGENAME = src.LOCALLANGUAGENAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.MEDICALAPPLICATION = src.MEDICALAPPLICATION,tgt.CONFIDENTIALAPPLICATION = src.CONFIDENTIALAPPLICATION,tgt.MARKET = src.MARKET,tgt.SEGMENT = src.SEGMENT,tgt.SUBSEGMENT = src.SUBSEGMENT,tgt.PROCESSINGMETHODERPID = src.PROCESSINGMETHODERPID,tgt.PROCESSINGMETHOD = src.PROCESSINGMETHOD,tgt.OEMERPID = src.OEMERPID,tgt.OEM = src.OEM,tgt.DESCRIPTION = src.DESCRIPTION,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.OPPORTUNITY = src.OPPORTUNITY,tgt.EAQOPPORTUNITY = src.EAQOPPORTUNITY,tgt.EAQOPPLASTUPDATE = src.EAQOPPLASTUPDATE,tgt.TOTALEAQUSAGE = src.TOTALEAQUSAGE,tgt.TOTALEAQUSAGELASTUPDATE = src.TOTALEAQUSAGELASTUPDATE,tgt.EAQOURSHARE = src.EAQOURSHARE,tgt.EAQOURSHARELASTUPDATE = src.EAQOURSHARELASTUPDATE,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,APPLICATIONGUID,APPLICATIONNAME,STATUS,STATUSREASON,LOCALLANGUAGENAME,ACCOUNTGUID,ACCOUNTERPID,BUSINESSUNIT,MEDICALAPPLICATION,CONFIDENTIALAPPLICATION,MARKET,SEGMENT,SUBSEGMENT,PROCESSINGMETHODERPID,PROCESSINGMETHOD,OEMERPID,OEM,DESCRIPTION,OPPORTUNITYGUID,OPPORTUNITY,EAQOPPORTUNITY,EAQOPPLASTUPDATE,TOTALEAQUSAGE,TOTALEAQUSAGELASTUPDATE,EAQOURSHARE,EAQOURSHARELASTUPDATE,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.APPLICATIONGUID,src.APPLICATIONNAME,src.STATUS,src.STATUSREASON,src.LOCALLANGUAGENAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.BUSINESSUNIT,src.MEDICALAPPLICATION,src.CONFIDENTIALAPPLICATION,src.MARKET,src.SEGMENT,src.SUBSEGMENT,src.PROCESSINGMETHODERPID,src.PROCESSINGMETHOD,src.OEMERPID,src.OEM,src.DESCRIPTION,src.OPPORTUNITYGUID,src.OPPORTUNITY,src.EAQOPPORTUNITY,src.EAQOPPLASTUPDATE,src.TOTALEAQUSAGE,src.TOTALEAQUSAGELASTUPDATE,src.EAQOURSHARE,src.EAQOURSHARELASTUPDATE,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_APPOINTMENTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_APPOINTMENTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_APPOINTMENTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ACTIVITYGUID = tgt.ACTIVITYGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.REGARDINGENTITYGUID = src.REGARDINGENTITYGUID,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDING = src.REGARDING,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.APPOINTMENTTYPE = src.APPOINTMENTTYPE,tgt.PRIORITY = src.PRIORITY,tgt.REQUIREDATTENDEES = src.REQUIREDATTENDEES,tgt.OPTIONALATTENDEES = src.OPTIONALATTENDEES,tgt.ORGANIZER = src.ORGANIZER,tgt.SUBJECT = src.SUBJECT,tgt.DESCRIPTION = src.DESCRIPTION,tgt.SCHEDULEDSTART = src.SCHEDULEDSTART,tgt.SCHEDULEDDURATION = src.SCHEDULEDDURATION,tgt.SCHEDULEDEND = src.SCHEDULEDEND,tgt.ACTUALSTART = src.ACTUALSTART,tgt.ACTUALDURATION = src.ACTUALDURATION,tgt.ACTUALEND = src.ACTUALEND,tgt.ACTIVITYREPORTGUID = src.ACTIVITYREPORTGUID,tgt.ACTIVITYREPORT = src.ACTIVITYREPORT,tgt.LOCATION = src.LOCATION,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYGUID,ACTIVITYTYPE,REGARDINGENTITYGUID,REGARDINGENTITY,REGARDING,BUSINESSUNIT,STATUS,STATUSREASON,APPOINTMENTTYPE,PRIORITY,REQUIREDATTENDEES,OPTIONALATTENDEES,ORGANIZER,SUBJECT,DESCRIPTION,SCHEDULEDSTART,SCHEDULEDDURATION,SCHEDULEDEND,ACTUALSTART,ACTUALDURATION,ACTUALEND,ACTIVITYREPORTGUID,ACTIVITYREPORT,LOCATION,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYGUID,src.ACTIVITYTYPE,src.REGARDINGENTITYGUID,src.REGARDINGENTITY,src.REGARDING,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.APPOINTMENTTYPE,src.PRIORITY,src.REQUIREDATTENDEES,src.OPTIONALATTENDEES,src.ORGANIZER,src.SUBJECT,src.DESCRIPTION,src.SCHEDULEDSTART,src.SCHEDULEDDURATION,src.SCHEDULEDEND,src.ACTUALSTART,src.ACTUALDURATION,src.ACTUALEND,src.ACTIVITYREPORTGUID,src.ACTIVITYREPORT,src.LOCATION,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_COMMENTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_COMMENTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_COMMENTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ACTIVITYGUID = tgt.ACTIVITYGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.REGARDINGENTITYGUID = src.REGARDINGENTITYGUID,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDING = src.REGARDING,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.COMMENTTYPE = src.COMMENTTYPE,tgt.PRIORITY = src.PRIORITY,tgt.HIGHLOW = src.HIGHLOW,tgt.COMMENT = src.COMMENT,tgt.DESCRIPTION = src.DESCRIPTION,tgt.ACTIVITYREPORTGUID = src.ACTIVITYREPORTGUID,tgt.ACTIVITYREPORT = src.ACTIVITYREPORT,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYGUID,ACTIVITYTYPE,REGARDINGENTITYGUID,REGARDINGENTITY,REGARDING,BUSINESSUNIT,STATUS,STATUSREASON,COMMENTTYPE,PRIORITY,HIGHLOW,COMMENT,DESCRIPTION,ACTIVITYREPORTGUID,ACTIVITYREPORT,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYGUID,src.ACTIVITYTYPE,src.REGARDINGENTITYGUID,src.REGARDINGENTITY,src.REGARDING,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.COMMENTTYPE,src.PRIORITY,src.HIGHLOW,src.COMMENT,src.DESCRIPTION,src.ACTIVITYREPORTGUID,src.ACTIVITYREPORT,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_COMPETITORS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_COMPETITORS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_COMPETITORS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.CompetitorGUID = tgt.CompetitorGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.COMPETITORGUID = src.COMPETITORGUID,tgt.COMPETITORERPID = src.COMPETITORERPID,tgt.COMPETITORNAME = src.COMPETITORNAME,tgt.WEBSITE = src.WEBSITE,tgt.STRENGTHS = src.STRENGTHS,tgt.WEAKNESSES = src.WEAKNESSES,tgt.CURRENCY = src.CURRENCY,tgt.ADDRESSLINE1 = src.ADDRESSLINE1,tgt.ADDRESSLINE2 = src.ADDRESSLINE2,tgt.ADDRESSLINE3 = src.ADDRESSLINE3,tgt.CITY = src.CITY,tgt.PROVINCE = src.PROVINCE,tgt.POSTALCODE = src.POSTALCODE,tgt.COUNTRY = src.COUNTRY,tgt.OPPORTUNITY = src.OPPORTUNITY,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,COMPETITORGUID,COMPETITORERPID,COMPETITORNAME,WEBSITE,STRENGTHS,WEAKNESSES,CURRENCY,ADDRESSLINE1,ADDRESSLINE2,ADDRESSLINE3,CITY,PROVINCE,POSTALCODE,COUNTRY,OPPORTUNITY,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.COMPETITORGUID,src.COMPETITORERPID,src.COMPETITORNAME,src.WEBSITE,src.STRENGTHS,src.WEAKNESSES,src.CURRENCY,src.ADDRESSLINE1,src.ADDRESSLINE2,src.ADDRESSLINE3,src.CITY,src.PROVINCE,src.POSTALCODE,src.COUNTRY,src.OPPORTUNITY,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_CONTACTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_CONTACTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_CONTACTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ContactGuid = tgt.ContactGuid
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.CONTACTGUID = src.CONTACTGUID,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.WEBSITE = src.WEBSITE,tgt.EXISTINGCONTACT = src.EXISTINGCONTACT,tgt.FIRSTNAME = src.FIRSTNAME,tgt.LASTNAME = src.LASTNAME,tgt.SALUTATION = src.SALUTATION,tgt.CONTACTTYPEERPID = src.CONTACTTYPEERPID,tgt.CONTACTTYPE = src.CONTACTTYPE,tgt.DEPARTMENT = src.DEPARTMENT,tgt.JOBTITLE = src.JOBTITLE,tgt.EMAIL = src.EMAIL,tgt.BUSINESSPHONE = src.BUSINESSPHONE,tgt.MOBILEPHONE = src.MOBILEPHONE,tgt.FAX = src.FAX,tgt.GENDER = src.GENDER,tgt.PERSONALNOTES = src.PERSONALNOTES,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.CHOOSEADDRESS = src.CHOOSEADDRESS,tgt.ADDRESSERPID = src.ADDRESSERPID,tgt.STREET1 = src.STREET1,tgt.STREET2 = src.STREET2,tgt.POSTALCODE = src.POSTALCODE,tgt.CITY = src.CITY,tgt.PROVINCE = src.PROVINCE,tgt.COUNTRYERPID = src.COUNTRYERPID,tgt.COUNTRY = src.COUNTRY,tgt.PREFERREDCONTACTMETHOD = src.PREFERREDCONTACTMETHOD,tgt.DONOTEMAIL = src.DONOTEMAIL,tgt.DONOTBULKEMAIL = src.DONOTBULKEMAIL,tgt.DONOTPHONE = src.DONOTPHONE,tgt.DONOTFAX = src.DONOTFAX,tgt.DONOTPOSTMAIL = src.DONOTPOSTMAIL,tgt.DONOTBULKPOSTMAIL = src.DONOTBULKPOSTMAIL,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,CONTACTGUID,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,LENERPID,OLEERPID,OLENAME,WEBSITE,EXISTINGCONTACT,FIRSTNAME,LASTNAME,SALUTATION,CONTACTTYPEERPID,CONTACTTYPE,DEPARTMENT,JOBTITLE,EMAIL,BUSINESSPHONE,MOBILEPHONE,FAX,GENDER,PERSONALNOTES,STATUS,STATUSREASON,CHOOSEADDRESS,ADDRESSERPID,STREET1,STREET2,POSTALCODE,CITY,PROVINCE,COUNTRYERPID,COUNTRY,PREFERREDCONTACTMETHOD,DONOTEMAIL,DONOTBULKEMAIL,DONOTPHONE,DONOTFAX,DONOTPOSTMAIL,DONOTBULKPOSTMAIL,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.CONTACTGUID,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.LENERPID,src.OLEERPID,src.OLENAME,src.WEBSITE,src.EXISTINGCONTACT,src.FIRSTNAME,src.LASTNAME,src.SALUTATION,src.CONTACTTYPEERPID,src.CONTACTTYPE,src.DEPARTMENT,src.JOBTITLE,src.EMAIL,src.BUSINESSPHONE,src.MOBILEPHONE,src.FAX,src.GENDER,src.PERSONALNOTES,src.STATUS,src.STATUSREASON,src.CHOOSEADDRESS,src.ADDRESSERPID,src.STREET1,src.STREET2,src.POSTALCODE,src.CITY,src.PROVINCE,src.COUNTRYERPID,src.COUNTRY,src.PREFERREDCONTACTMETHOD,src.DONOTEMAIL,src.DONOTBULKEMAIL,src.DONOTPHONE,src.DONOTFAX,src.DONOTPOSTMAIL,src.DONOTBULKPOSTMAIL,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_EMAILS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_EMAILS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_EMAILS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ACTIVITYGUID = tgt.ACTIVITYGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.REGARDINGENTITYGUID = src.REGARDINGENTITYGUID,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDING = src.REGARDING,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.DIRECTION = src.DIRECTION,tgt.PRIORITY = src.PRIORITY,tgt.SUBJECT = src.SUBJECT,tgt.EMAILFROM = src.EMAILFROM,tgt.EMAILTO = src.EMAILTO,tgt.EMAILCC = src.EMAILCC,tgt.EMAILBCC = src.EMAILBCC,tgt.SCHEDULEDSTART = src.SCHEDULEDSTART,tgt.SCHEDULEDDURATION = src.SCHEDULEDDURATION,tgt.SCHEDULEDEND = src.SCHEDULEDEND,tgt.ACTUALSTART = src.ACTUALSTART,tgt.ACTUALDURATION = src.ACTUALDURATION,tgt.ACTUALEND = src.ACTUALEND,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYGUID,ACTIVITYTYPE,REGARDINGENTITYGUID,REGARDINGENTITY,REGARDING,BUSINESSUNIT,STATUS,STATUSREASON,DIRECTION,PRIORITY,SUBJECT,EMAILFROM,EMAILTO,EMAILCC,EMAILBCC,SCHEDULEDSTART,SCHEDULEDDURATION,SCHEDULEDEND,ACTUALSTART,ACTUALDURATION,ACTUALEND,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYGUID,src.ACTIVITYTYPE,src.REGARDINGENTITYGUID,src.REGARDINGENTITY,src.REGARDING,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.DIRECTION,src.PRIORITY,src.SUBJECT,src.EMAILFROM,src.EMAILTO,src.EMAILCC,src.EMAILBCC,src.SCHEDULEDSTART,src.SCHEDULEDDURATION,src.SCHEDULEDEND,src.ACTUALSTART,src.ACTUALDURATION,src.ACTUALEND,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_LEADS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_LEADS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_LEADS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.LeadGuid = tgt.LeadGuid
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.LEADGUID = src.LEADGUID,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.UOMSYSTEMERPID = src.UOMSYSTEMERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.PREFERREDCURRENCY = src.PREFERREDCURRENCY,tgt.VATNO = src.VATNO,tgt.COUNTRYERPID = src.COUNTRYERPID,tgt.COUNTRY = src.COUNTRY,tgt.WEBSITE = src.WEBSITE,tgt.LANGUAGEERPID = src.LANGUAGEERPID,tgt.LANGUAGE = src.LANGUAGE,tgt.EXISTINGCONTACT = src.EXISTINGCONTACT,tgt.FIRSTNAME = src.FIRSTNAME,tgt.LASTNAME = src.LASTNAME,tgt.SALUTATION = src.SALUTATION,tgt.JOBTITLE = src.JOBTITLE,tgt.BUSINESSPHONE = src.BUSINESSPHONE,tgt.MOBILEPHONE = src.MOBILEPHONE,tgt.EMAIL = src.EMAIL,tgt.LEADSOURCE = src.LEADSOURCE,tgt.TERRITORYERPID = src.TERRITORYERPID,tgt.TERRITORY = src.TERRITORY,tgt.RATING = src.RATING,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.PROVINCEERPID = src.PROVINCEERPID,tgt.PROVINCE = src.PROVINCE,tgt.CITY = src.CITY,tgt.POSTALCODE = src.POSTALCODE,tgt.STREET1 = src.STREET1,tgt.STREET2 = src.STREET2,tgt.STREET3 = src.STREET3,tgt.QUALIFICATIONCOMMENTS = src.QUALIFICATIONCOMMENTS,tgt.UOMSET = src.UOMSET,tgt.UOM = src.UOM,tgt.ESTQUANTITY = src.ESTQUANTITY,tgt.PRODUCTGROUPERPID = src.PRODUCTGROUPERPID,tgt.PRODUCTGROUP = src.PRODUCTGROUP,tgt.PRODUCTSUBGROUPERPID = src.PRODUCTSUBGROUPERPID,tgt.PRODUCTSUBGROUP = src.PRODUCTSUBGROUP,tgt.BRANDERPID = src.BRANDERPID,tgt.BRAND = src.BRAND,tgt.GRADE = src.GRADE,tgt.RAV_APPLICATIONNAME = src.RAV_APPLICATIONNAME,tgt.MEDICALAPPLICATION = src.MEDICALAPPLICATION,tgt.CONFIDENTIALAPPLICATION = src.CONFIDENTIALAPPLICATION,tgt.MARKET = src.MARKET,tgt.SEGMENT = src.SEGMENT,tgt.SUBSEGMENT = src.SUBSEGMENT,tgt.OEM = src.OEM,tgt.APPLDESCRIPTION = src.APPLDESCRIPTION,tgt.NUMBEROFEMPLOYEES = src.NUMBEROFEMPLOYEES,tgt.PROCESSINGMETHOD = src.PROCESSINGMETHOD,tgt.NUMBEROFMACHINES = src.NUMBEROFMACHINES,tgt.ESTQUANTITYSI = src.ESTQUANTITYSI,tgt.ESTQUANTITYUS = src.ESTQUANTITYUS,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,LEADGUID,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,LENERPID,OLEERPID,OLENAME,UOMSYSTEMERPID,UOMSYSTEM,PREFERREDCURRENCY,VATNO,COUNTRYERPID,COUNTRY,WEBSITE,LANGUAGEERPID,LANGUAGE,EXISTINGCONTACT,FIRSTNAME,LASTNAME,SALUTATION,JOBTITLE,BUSINESSPHONE,MOBILEPHONE,EMAIL,LEADSOURCE,TERRITORYERPID,TERRITORY,RATING,STATUS,STATUSREASON,PROVINCEERPID,PROVINCE,CITY,POSTALCODE,STREET1,STREET2,STREET3,QUALIFICATIONCOMMENTS,UOMSET,UOM,ESTQUANTITY,PRODUCTGROUPERPID,PRODUCTGROUP,PRODUCTSUBGROUPERPID,PRODUCTSUBGROUP,BRANDERPID,BRAND,GRADE,RAV_APPLICATIONNAME,MEDICALAPPLICATION,CONFIDENTIALAPPLICATION,MARKET,SEGMENT,SUBSEGMENT,OEM,APPLDESCRIPTION,NUMBEROFEMPLOYEES,PROCESSINGMETHOD,NUMBEROFMACHINES,ESTQUANTITYSI,ESTQUANTITYUS,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.LEADGUID,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.LENERPID,src.OLEERPID,src.OLENAME,src.UOMSYSTEMERPID,src.UOMSYSTEM,src.PREFERREDCURRENCY,src.VATNO,src.COUNTRYERPID,src.COUNTRY,src.WEBSITE,src.LANGUAGEERPID,src.LANGUAGE,src.EXISTINGCONTACT,src.FIRSTNAME,src.LASTNAME,src.SALUTATION,src.JOBTITLE,src.BUSINESSPHONE,src.MOBILEPHONE,src.EMAIL,src.LEADSOURCE,src.TERRITORYERPID,src.TERRITORY,src.RATING,src.STATUS,src.STATUSREASON,src.PROVINCEERPID,src.PROVINCE,src.CITY,src.POSTALCODE,src.STREET1,src.STREET2,src.STREET3,src.QUALIFICATIONCOMMENTS,src.UOMSET,src.UOM,src.ESTQUANTITY,src.PRODUCTGROUPERPID,src.PRODUCTGROUP,src.PRODUCTSUBGROUPERPID,src.PRODUCTSUBGROUP,src.BRANDERPID,src.BRAND,src.GRADE,src.RAV_APPLICATIONNAME,src.MEDICALAPPLICATION,src.CONFIDENTIALAPPLICATION,src.MARKET,src.SEGMENT,src.SUBSEGMENT,src.OEM,src.APPLDESCRIPTION,src.NUMBEROFEMPLOYEES,src.PROCESSINGMETHOD,src.NUMBEROFMACHINES,src.ESTQUANTITYSI,src.ESTQUANTITYUS,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_OPPORTUNITIES AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_OPPORTUNITIES src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_OPPORTUNITIES)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.OppGuid = tgt.OppGuid
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.OPPGUID = src.OPPGUID,tgt.OPPNAME = src.OPPNAME,tgt.OPPTYPE = src.OPPTYPE,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.EAQ = src.EAQ,tgt.UOM = src.UOM,tgt.PRODGROUPERPID = src.PRODGROUPERPID,tgt.PRODGROUPNAME = src.PRODGROUPNAME,tgt.PRODSUBGROUPERPID = src.PRODSUBGROUPERPID,tgt.PRODSUBGROUPNAME = src.PRODSUBGROUPNAME,tgt.BRANDERPID = src.BRANDERPID,tgt.BRANDNAME = src.BRANDNAME,tgt.RMBRAND = src.RMBRAND,tgt.GRADENAME = src.GRADENAME,tgt.APPLICATIONGUID = src.APPLICATIONGUID,tgt.APPLICATIONNAME = src.APPLICATIONNAME,tgt.OPPDESCRIPTION = src.OPPDESCRIPTION,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.PRIMARYCONTACTGUID = src.PRIMARYCONTACTGUID,tgt.PRIMARYCONTACT = src.PRIMARYCONTACT,tgt.ESTCLOSEDATE = src.ESTCLOSEDATE,tgt.MEDICALAPPL = src.MEDICALAPPL,tgt.LOSTTOCOMPETITOR = src.LOSTTOCOMPETITOR,tgt.OPPORTUNITYCOMPGUID = src.OPPORTUNITYCOMPGUID,tgt.ACTUALCLOSEDATE = src.ACTUALCLOSEDATE,tgt.CONFIRMEAQ = src.CONFIRMEAQ,tgt.SELLERFAVORITE = src.SELLERFAVORITE,tgt.PMFAVORITE = src.PMFAVORITE,tgt.PRIORITY = src.PRIORITY,tgt.POTENTIALSUCCES = src.POTENTIALSUCCES,tgt.TRANSACTIONCURR = src.TRANSACTIONCURR,tgt.PRIMPRODERPID = src.PRIMPRODERPID,tgt.PRIMPRODNAME = src.PRIMPRODNAME,tgt.PRODUCTSEGMENT = src.PRODUCTSEGMENT,tgt.PRIMPRODBRANDERPID = src.PRIMPRODBRANDERPID,tgt.PRIMPRODBRANDNAME = src.PRIMPRODBRANDNAME,tgt.PRIMRMBRAND = src.PRIMRMBRAND,tgt.PRIMPRODGRADENAME = src.PRIMPRODGRADENAME,tgt.PRIMPRODGROUPERPID = src.PRIMPRODGROUPERPID,tgt.PRIMPRODGROUPNAME = src.PRIMPRODGROUPNAME,tgt.PRIMPRODSUBGROUPERPID = src.PRIMPRODSUBGROUPERPID,tgt.PRIMPRODSUBGROUPNAME = src.PRIMPRODSUBGROUPNAME,tgt.PRIMPRODCOLORERPID = src.PRIMPRODCOLORERPID,tgt.PRIMPRODCOLORNAME = src.PRIMPRODCOLORNAME,tgt.PRIMPRODUOMSET = src.PRIMPRODUOMSET,tgt.PRIMPRODMANAGER = src.PRIMPRODMANAGER,tgt.PRIMPRODMANAGERRAVID = src.PRIMPRODMANAGERRAVID,tgt.PRIMPRODMANAGERPERSERPID = src.PRIMPRODMANAGERPERSERPID,tgt.PRIMPRODCOORDINATER = src.PRIMPRODCOORDINATER,tgt.PRIMPRODCOORDINATORRAVID = src.PRIMPRODCOORDINATORRAVID,tgt.PRIMPRODCOORDINATORPERSERPID = src.PRIMPRODCOORDINATORPERSERPID,tgt.SUPPLIERGUID = src.SUPPLIERGUID,tgt.PRIMPRODSUPPLIERERPID = src.PRIMPRODSUPPLIERERPID,tgt.PRIMPRODSUPPLIER = src.PRIMPRODSUPPLIER,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.QUANTITYSI = src.QUANTITYSI,tgt.QUANTITYUS = src.QUANTITYUS,tgt.TIMEINDEV = src.TIMEINDEV,tgt.TIMEINDEVUNIT = src.TIMEINDEVUNIT,tgt.TIMEINPROP = src.TIMEINPROP,tgt.TIMEINPROPUNIT = src.TIMEINPROPUNIT,tgt.TIMEINSAMP = src.TIMEINSAMP,tgt.TIMEINSAMPUNIT = src.TIMEINSAMPUNIT,tgt.TIMEINCLOSE = src.TIMEINCLOSE,tgt.TIMEINCLOSEUNIT = src.TIMEINCLOSEUNIT,tgt.MRFPROCEDURE = src.MRFPROCEDURE,tgt.LEADGUID = src.LEADGUID,tgt.ORIGINATINGLEAD = src.ORIGINATINGLEAD,tgt.PRODUCTUSAGEGUID = src.PRODUCTUSAGEGUID,tgt.PRODUCTUSAGE = src.PRODUCTUSAGE,tgt.OURSHAREGUID = src.OURSHAREGUID,tgt.OURSHARE = src.OURSHARE,tgt.COMPETITORSHAREGUID = src.COMPETITORSHAREGUID,tgt.COMPETITORSHARE = src.COMPETITORSHARE,tgt.PIPELINEPHASE = src.PIPELINEPHASE,tgt.RPCLENTITY = src.RPCLENTITY,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,OPPGUID,OPPNAME,OPPTYPE,STATUS,STATUSREASON,EAQ,UOM,PRODGROUPERPID,PRODGROUPNAME,PRODSUBGROUPERPID,PRODSUBGROUPNAME,BRANDERPID,BRANDNAME,RMBRAND,GRADENAME,APPLICATIONGUID,APPLICATIONNAME,OPPDESCRIPTION,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,PRIMARYCONTACTGUID,PRIMARYCONTACT,ESTCLOSEDATE,MEDICALAPPL,LOSTTOCOMPETITOR,OPPORTUNITYCOMPGUID,ACTUALCLOSEDATE,CONFIRMEAQ,SELLERFAVORITE,PMFAVORITE,PRIORITY,POTENTIALSUCCES,TRANSACTIONCURR,PRIMPRODERPID,PRIMPRODNAME,PRODUCTSEGMENT,PRIMPRODBRANDERPID,PRIMPRODBRANDNAME,PRIMRMBRAND,PRIMPRODGRADENAME,PRIMPRODGROUPERPID,PRIMPRODGROUPNAME,PRIMPRODSUBGROUPERPID,PRIMPRODSUBGROUPNAME,PRIMPRODCOLORERPID,PRIMPRODCOLORNAME,PRIMPRODUOMSET,PRIMPRODMANAGER,PRIMPRODMANAGERRAVID,PRIMPRODMANAGERPERSERPID,PRIMPRODCOORDINATER,PRIMPRODCOORDINATORRAVID,PRIMPRODCOORDINATORPERSERPID,SUPPLIERGUID,PRIMPRODSUPPLIERERPID,PRIMPRODSUPPLIER,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,UOMSYSTEM,QUANTITYSI,QUANTITYUS,TIMEINDEV,TIMEINDEVUNIT,TIMEINPROP,TIMEINPROPUNIT,TIMEINSAMP,TIMEINSAMPUNIT,TIMEINCLOSE,TIMEINCLOSEUNIT,MRFPROCEDURE,LEADGUID,ORIGINATINGLEAD,PRODUCTUSAGEGUID,PRODUCTUSAGE,OURSHAREGUID,OURSHARE,COMPETITORSHAREGUID,COMPETITORSHARE,PIPELINEPHASE,RPCLENTITY,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.OPPGUID,src.OPPNAME,src.OPPTYPE,src.STATUS,src.STATUSREASON,src.EAQ,src.UOM,src.PRODGROUPERPID,src.PRODGROUPNAME,src.PRODSUBGROUPERPID,src.PRODSUBGROUPNAME,src.BRANDERPID,src.BRANDNAME,src.RMBRAND,src.GRADENAME,src.APPLICATIONGUID,src.APPLICATIONNAME,src.OPPDESCRIPTION,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.PRIMARYCONTACTGUID,src.PRIMARYCONTACT,src.ESTCLOSEDATE,src.MEDICALAPPL,src.LOSTTOCOMPETITOR,src.OPPORTUNITYCOMPGUID,src.ACTUALCLOSEDATE,src.CONFIRMEAQ,src.SELLERFAVORITE,src.PMFAVORITE,src.PRIORITY,src.POTENTIALSUCCES,src.TRANSACTIONCURR,src.PRIMPRODERPID,src.PRIMPRODNAME,src.PRODUCTSEGMENT,src.PRIMPRODBRANDERPID,src.PRIMPRODBRANDNAME,src.PRIMRMBRAND,src.PRIMPRODGRADENAME,src.PRIMPRODGROUPERPID,src.PRIMPRODGROUPNAME,src.PRIMPRODSUBGROUPERPID,src.PRIMPRODSUBGROUPNAME,src.PRIMPRODCOLORERPID,src.PRIMPRODCOLORNAME,src.PRIMPRODUOMSET,src.PRIMPRODMANAGER,src.PRIMPRODMANAGERRAVID,src.PRIMPRODMANAGERPERSERPID,src.PRIMPRODCOORDINATER,src.PRIMPRODCOORDINATORRAVID,src.PRIMPRODCOORDINATORPERSERPID,src.SUPPLIERGUID,src.PRIMPRODSUPPLIERERPID,src.PRIMPRODSUPPLIER,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.UOMSYSTEM,src.QUANTITYSI,src.QUANTITYUS,src.TIMEINDEV,src.TIMEINDEVUNIT,src.TIMEINPROP,src.TIMEINPROPUNIT,src.TIMEINSAMP,src.TIMEINSAMPUNIT,src.TIMEINCLOSE,src.TIMEINCLOSEUNIT,src.MRFPROCEDURE,src.LEADGUID,src.ORIGINATINGLEAD,src.PRODUCTUSAGEGUID,src.PRODUCTUSAGE,src.OURSHAREGUID,src.OURSHARE,src.COMPETITORSHAREGUID,src.COMPETITORSHARE,src.PIPELINEPHASE,src.RPCLENTITY,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_OPPORTUNITYCOMPETITORS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_OPPORTUNITYCOMPETITORS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_OPPORTUNITYCOMPETITORS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.OPPORTUNITYCOMPETITORGUID = tgt.OPPORTUNITYCOMPETITORGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.SOURCEID = src.SOURCEID,tgt.COMPETITORGUID = src.COMPETITORGUID,tgt.OPPORTUNITYCOMPETITORGUID = src.OPPORTUNITYCOMPETITORGUID,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.BRANDERPID = src.BRANDERPID,tgt.BRANDNAME = src.BRANDNAME,tgt.GRADENAME = src.GRADENAME,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.OPPCOMPCOMMENT = src.OPPCOMPCOMMENT,tgt.VOLUME = src.VOLUME,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(SOURCEID,COMPETITORGUID,OPPORTUNITYCOMPETITORGUID,OPPORTUNITYGUID,STATUS,STATUSREASON,BRANDERPID,BRANDNAME,GRADENAME,BUSINESSUNIT,OPPCOMPCOMMENT,VOLUME,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.SOURCEID,src.COMPETITORGUID,src.OPPORTUNITYCOMPETITORGUID,src.OPPORTUNITYGUID,src.STATUS,src.STATUSREASON,src.BRANDERPID,src.BRANDNAME,src.GRADENAME,src.BUSINESSUNIT,src.OPPCOMPCOMMENT,src.VOLUME,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_OPPORTUNITYPRODUCTS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_OPPORTUNITYPRODUCTS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_OPPORTUNITYPRODUCTS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.OPPPRODUCTGUID = tgt.OPPPRODUCTGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.OPPPRODUCTGUID = src.OPPPRODUCTGUID,tgt.OPPPRODUCTNAME = src.OPPPRODUCTNAME,tgt.PRODUCTSEGMENT = src.PRODUCTSEGMENT,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.WRITEIN = src.WRITEIN,tgt.OPPPRODUCTERPID = src.OPPPRODUCTERPID,tgt.EXISTINGPRODUCTNAME = src.EXISTINGPRODUCTNAME,tgt.SUPPLIERGUID = src.SUPPLIERGUID,tgt.SUPPLIERID = src.SUPPLIERID,tgt.SUPPLIERNAME = src.SUPPLIERNAME,tgt.QUANTITY = src.QUANTITY,tgt.UOM = src.UOM,tgt.PRICEPERUNIT = src.PRICEPERUNIT,tgt.CURRENCY = src.CURRENCY,tgt.ISPRIMARY = src.ISPRIMARY,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,OPPPRODUCTGUID,OPPPRODUCTNAME,PRODUCTSEGMENT,OPPORTUNITYGUID,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,WRITEIN,OPPPRODUCTERPID,EXISTINGPRODUCTNAME,SUPPLIERGUID,SUPPLIERID,SUPPLIERNAME,QUANTITY,UOM,PRICEPERUNIT,CURRENCY,ISPRIMARY,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.OPPPRODUCTGUID,src.OPPPRODUCTNAME,src.PRODUCTSEGMENT,src.OPPORTUNITYGUID,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.WRITEIN,src.OPPPRODUCTERPID,src.EXISTINGPRODUCTNAME,src.SUPPLIERGUID,src.SUPPLIERID,src.SUPPLIERNAME,src.QUANTITY,src.UOM,src.PRICEPERUNIT,src.CURRENCY,src.ISPRIMARY,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_PHONECALLS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_PHONECALLS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_PHONECALLS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ACTIVITYGUID = tgt.ACTIVITYGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.REGARDINGENTITYGUID = src.REGARDINGENTITYGUID,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDING = src.REGARDING,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.DIRECTION = src.DIRECTION,tgt.PRIORITY = src.PRIORITY,tgt.SUBJECT = src.SUBJECT,tgt.DESCRIPTION = src.DESCRIPTION,tgt.CALLFROM = src.CALLFROM,tgt.CALLTO = src.CALLTO,tgt.SCHEDULEDSTART = src.SCHEDULEDSTART,tgt.SCHEDULEDDURATION = src.SCHEDULEDDURATION,tgt.SCHEDULEDEND = src.SCHEDULEDEND,tgt.ACTUALSTART = src.ACTUALSTART,tgt.ACTUALDURATION = src.ACTUALDURATION,tgt.ACTUALEND = src.ACTUALEND,tgt.ACTIVITYREPORTGUID = src.ACTIVITYREPORTGUID,tgt.ACTIVITYREPORT = src.ACTIVITYREPORT,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYGUID,ACTIVITYTYPE,REGARDINGENTITYGUID,REGARDINGENTITY,REGARDING,BUSINESSUNIT,STATUS,STATUSREASON,DIRECTION,PRIORITY,SUBJECT,DESCRIPTION,CALLFROM,CALLTO,SCHEDULEDSTART,SCHEDULEDDURATION,SCHEDULEDEND,ACTUALSTART,ACTUALDURATION,ACTUALEND,ACTIVITYREPORTGUID,ACTIVITYREPORT,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYGUID,src.ACTIVITYTYPE,src.REGARDINGENTITYGUID,src.REGARDINGENTITY,src.REGARDING,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.DIRECTION,src.PRIORITY,src.SUBJECT,src.DESCRIPTION,src.CALLFROM,src.CALLTO,src.SCHEDULEDSTART,src.SCHEDULEDDURATION,src.SCHEDULEDEND,src.ACTUALSTART,src.ACTUALDURATION,src.ACTUALEND,src.ACTIVITYREPORTGUID,src.ACTIVITYREPORT,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_PRODUCTUSAGES AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_PRODUCTUSAGES src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_PRODUCTUSAGES)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.PRODUCTUSAGEGUID = tgt.PRODUCTUSAGEGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.PRODUCTUSAGEGUID = src.PRODUCTUSAGEGUID,tgt.PRODUCTUSAGE = src.PRODUCTUSAGE,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.DATAQUALITYRATING = src.DATAQUALITYRATING,tgt.CONTACTGUID = src.CONTACTGUID,tgt.FULLNAME = src.FULLNAME,tgt.PRODUCTINPORTFOLIO = src.PRODUCTINPORTFOLIO,tgt.PRODUCT = src.PRODUCT,tgt.PRODUCTSEGMENT = src.PRODUCTSEGMENT,tgt.PRODGROUPERPID = src.PRODGROUPERPID,tgt.PRODGROUP = src.PRODGROUP,tgt.PRODSUBGROUPERPID = src.PRODSUBGROUPERPID,tgt.PRODSUBGROUP = src.PRODSUBGROUP,tgt.POTENTIALCATEGORY = src.POTENTIALCATEGORY,tgt.ENDSON = src.ENDSON,tgt.GRADE = src.GRADE,tgt.BRANDERPID = src.BRANDERPID,tgt.BRAND = src.BRAND,tgt.RMBRAND = src.RMBRAND,tgt.PRODUCERSUPPLIER = src.PRODUCERSUPPLIER,tgt.PRODUCERCOLORCODE = src.PRODUCERCOLORCODE,tgt.COLORERPID = src.COLORERPID,tgt.COLOR = src.COLOR,tgt.PRODUCTERPID = src.PRODUCTERPID,tgt.UOM = src.UOM,tgt.TOTALEAQ = src.TOTALEAQ,tgt.OURSHAREEAQ = src.OURSHAREEAQ,tgt.COMPETITORSHAREEAQ = src.COMPETITORSHAREEAQ,tgt.BUDGET = src.BUDGET,tgt.YTDBUDGET = src.YTDBUDGET,tgt.YTD = src.YTD,tgt.LASTORDERDATE = src.LASTORDERDATE,tgt.COMPETITORSHARES = src.COMPETITORSHARES,tgt.COMPETITORGUID = src.COMPETITORGUID,tgt.PRIMARYCOMPETITORERPID = src.PRIMARYCOMPETITORERPID,tgt.PRIMARYCOMPETITOR = src.PRIMARYCOMPETITOR,tgt.UOMSYSTEMERPID = src.UOMSYSTEMERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.UOMNAME = src.UOMNAME,tgt.UOMSET = src.UOMSET,tgt.TOTALEAQSI = src.TOTALEAQSI,tgt.TOTALEAQUS = src.TOTALEAQUS,tgt.OURSHAREEAQSI = src.OURSHAREEAQSI,tgt.OURSHAREEAQUS = src.OURSHAREEAQUS,tgt.COMPETITORSHAREEAQSI = src.COMPETITORSHAREEAQSI,tgt.COMPETITORSHAREEAQUS = src.COMPETITORSHAREEAQUS,tgt.BUDGETSI = src.BUDGETSI,tgt.BUDGETUS = src.BUDGETUS,tgt.YTDBUDGETSI = src.YTDBUDGETSI,tgt.YTDBUDGETUS = src.YTDBUDGETUS,tgt.YTDSI = src.YTDSI,tgt.YTDUS = src.YTDUS,tgt.CURRENCY = src.CURRENCY,tgt.LEADGUID = src.LEADGUID,tgt.ORIGINATINGLEAD = src.ORIGINATINGLEAD,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.ORIGINATINGOPPORTUNITY = src.ORIGINATINGOPPORTUNITY,tgt.QUOTEGUID = src.QUOTEGUID,tgt.ORIGINATINGQUOTE = src.ORIGINATINGQUOTE,tgt.APPLICATIONGUID = src.APPLICATIONGUID,tgt.ORIGINATINGAPPLICATION = src.ORIGINATINGAPPLICATION,tgt.ORDERHISTORYGUID = src.ORDERHISTORYGUID,tgt.CURRENTYEARORDERHISTORY = src.CURRENTYEARORDERHISTORY,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,PRODUCTUSAGEGUID,PRODUCTUSAGE,STATUS,STATUSREASON,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,DATAQUALITYRATING,CONTACTGUID,FULLNAME,PRODUCTINPORTFOLIO,PRODUCT,PRODUCTSEGMENT,PRODGROUPERPID,PRODGROUP,PRODSUBGROUPERPID,PRODSUBGROUP,POTENTIALCATEGORY,ENDSON,GRADE,BRANDERPID,BRAND,RMBRAND,PRODUCERSUPPLIER,PRODUCERCOLORCODE,COLORERPID,COLOR,PRODUCTERPID,UOM,TOTALEAQ,OURSHAREEAQ,COMPETITORSHAREEAQ,BUDGET,YTDBUDGET,YTD,LASTORDERDATE,COMPETITORSHARES,COMPETITORGUID,PRIMARYCOMPETITORERPID,PRIMARYCOMPETITOR,UOMSYSTEMERPID,UOMSYSTEM,UOMNAME,UOMSET,TOTALEAQSI,TOTALEAQUS,OURSHAREEAQSI,OURSHAREEAQUS,COMPETITORSHAREEAQSI,COMPETITORSHAREEAQUS,BUDGETSI,BUDGETUS,YTDBUDGETSI,YTDBUDGETUS,YTDSI,YTDUS,CURRENCY,LEADGUID,ORIGINATINGLEAD,OPPORTUNITYGUID,ORIGINATINGOPPORTUNITY,QUOTEGUID,ORIGINATINGQUOTE,APPLICATIONGUID,ORIGINATINGAPPLICATION,ORDERHISTORYGUID,CURRENTYEARORDERHISTORY,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.PRODUCTUSAGEGUID,src.PRODUCTUSAGE,src.STATUS,src.STATUSREASON,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.DATAQUALITYRATING,src.CONTACTGUID,src.FULLNAME,src.PRODUCTINPORTFOLIO,src.PRODUCT,src.PRODUCTSEGMENT,src.PRODGROUPERPID,src.PRODGROUP,src.PRODSUBGROUPERPID,src.PRODSUBGROUP,src.POTENTIALCATEGORY,src.ENDSON,src.GRADE,src.BRANDERPID,src.BRAND,src.RMBRAND,src.PRODUCERSUPPLIER,src.PRODUCERCOLORCODE,src.COLORERPID,src.COLOR,src.PRODUCTERPID,src.UOM,src.TOTALEAQ,src.OURSHAREEAQ,src.COMPETITORSHAREEAQ,src.BUDGET,src.YTDBUDGET,src.YTD,src.LASTORDERDATE,src.COMPETITORSHARES,src.COMPETITORGUID,src.PRIMARYCOMPETITORERPID,src.PRIMARYCOMPETITOR,src.UOMSYSTEMERPID,src.UOMSYSTEM,src.UOMNAME,src.UOMSET,src.TOTALEAQSI,src.TOTALEAQUS,src.OURSHAREEAQSI,src.OURSHAREEAQUS,src.COMPETITORSHAREEAQSI,src.COMPETITORSHAREEAQUS,src.BUDGETSI,src.BUDGETUS,src.YTDBUDGETSI,src.YTDBUDGETUS,src.YTDSI,src.YTDUS,src.CURRENCY,src.LEADGUID,src.ORIGINATINGLEAD,src.OPPORTUNITYGUID,src.ORIGINATINGOPPORTUNITY,src.QUOTEGUID,src.ORIGINATINGQUOTE,src.APPLICATIONGUID,src.ORIGINATINGAPPLICATION,src.ORDERHISTORYGUID,src.CURRENTYEARORDERHISTORY,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_QUOTEDETAILS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_QUOTEDETAILS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_QUOTEDETAILS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.QUOTEDETAILGUID = tgt.QUOTEDETAILGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.QUOTEDETAILGUID = src.QUOTEDETAILGUID,tgt.QUOTEDETAILNAME = src.QUOTEDETAILNAME,tgt.QUOTEGUID = src.QUOTEGUID,tgt.QUOTENAME = src.QUOTENAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.PRODUCTUSAGE = src.PRODUCTUSAGE,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.PRODUCTERPID = src.PRODUCTERPID,tgt.PRODUCTNAME = src.PRODUCTNAME,tgt.PRODUCTSEGMENT = src.PRODUCTSEGMENT,tgt.PACAKAGING = src.PACAKAGING,tgt.QUANTITY = src.QUANTITY,tgt.QUANTITYSI = src.QUANTITYSI,tgt.QUANTITYUS = src.QUANTITYUS,tgt.UOM = src.UOM,tgt.PRICEPERUNIT = src.PRICEPERUNIT,tgt.PRICEPERUNITSI = src.PRICEPERUNITSI,tgt.PRICEPERUNITUS = src.PRICEPERUNITUS,tgt.CURRENCY = src.CURRENCY,tgt.ADDITIONALINFO = src.ADDITIONALINFO,tgt.NUMBEROFORDERREQUESTS = src.NUMBEROFORDERREQUESTS,tgt.ROLLUPLASTUPDATED = src.ROLLUPLASTUPDATED,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,QUOTEDETAILGUID,QUOTEDETAILNAME,QUOTEGUID,QUOTENAME,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,PRODUCTUSAGE,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,PRODUCTERPID,PRODUCTNAME,PRODUCTSEGMENT,PACAKAGING,QUANTITY,QUANTITYSI,QUANTITYUS,UOM,PRICEPERUNIT,PRICEPERUNITSI,PRICEPERUNITUS,CURRENCY,ADDITIONALINFO,NUMBEROFORDERREQUESTS,ROLLUPLASTUPDATED,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.QUOTEDETAILGUID,src.QUOTEDETAILNAME,src.QUOTEGUID,src.QUOTENAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.PRODUCTUSAGE,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.PRODUCTERPID,src.PRODUCTNAME,src.PRODUCTSEGMENT,src.PACAKAGING,src.QUANTITY,src.QUANTITYSI,src.QUANTITYUS,src.UOM,src.PRICEPERUNIT,src.PRICEPERUNITSI,src.PRICEPERUNITUS,src.CURRENCY,src.ADDITIONALINFO,src.NUMBEROFORDERREQUESTS,src.ROLLUPLASTUPDATED,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_QUOTES AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_QUOTES src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_QUOTES)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.QUOTEGUID = tgt.QUOTEGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.QUOTEGUID = src.QUOTEGUID,tgt.QUOTENAME = src.QUOTENAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.REVISIONNUMBER = src.REVISIONNUMBER,tgt.EFFECTIVEFROM = src.EFFECTIVEFROM,tgt.EFFICTIVETO = src.EFFICTIVETO,tgt.SHIPPINGERPID = src.SHIPPINGERPID,tgt.SHIPPINGADDRESS = src.SHIPPINGADDRESS,tgt.BILLINGADDRESSERPID = src.BILLINGADDRESSERPID,tgt.BILLINGADDRESS = src.BILLINGADDRESS,tgt.WAREHOUSEADDRESSERPID = src.WAREHOUSEADDRESSERPID,tgt.WAREHOUSEADDRESS = src.WAREHOUSEADDRESS,tgt.INCOTERMERPID = src.INCOTERMERPID,tgt.INCOTERM = src.INCOTERM,tgt.DESCRIPTION = src.DESCRIPTION,tgt.UOMSYSERPID = src.UOMSYSERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.CURRENCY = src.CURRENCY,tgt.PRIMARYCONTACTGUID = src.PRIMARYCONTACTGUID,tgt.PRIMARYCONTACT = src.PRIMARYCONTACT,tgt.SALESPERSON = src.SALESPERSON,tgt.SALESPERSONRAVID = src.SALESPERSONRAVID,tgt.SALESPERSERPID = src.SALESPERSERPID,tgt.FOLLUWUP = src.FOLLUWUP,tgt.FOLLOWUPSTATUS = src.FOLLOWUPSTATUS,tgt.LASTQUOTEGENERATEDBY = src.LASTQUOTEGENERATEDBY,tgt.LASTQUOTEBYRAVID = src.LASTQUOTEBYRAVID,tgt.LASTQUOTEBYERPID = src.LASTQUOTEBYERPID,tgt.LASTQUOTEGENERATEDON = src.LASTQUOTEGENERATEDON,tgt.LASTQUOTETEMPLATE = src.LASTQUOTETEMPLATE,tgt.PAYMENTCONDITION1 = src.PAYMENTCONDITION1,tgt.DISCOUNTPERCENTAGE1 = src.DISCOUNTPERCENTAGE1,tgt.PAYMENTCONDITION2 = src.PAYMENTCONDITION2,tgt.DISCOUNTPERCENTAGE2 = src.DISCOUNTPERCENTAGE2,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,QUOTEGUID,QUOTENAME,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,STATUS,STATUSREASON,REVISIONNUMBER,EFFECTIVEFROM,EFFICTIVETO,SHIPPINGERPID,SHIPPINGADDRESS,BILLINGADDRESSERPID,BILLINGADDRESS,WAREHOUSEADDRESSERPID,WAREHOUSEADDRESS,INCOTERMERPID,INCOTERM,DESCRIPTION,UOMSYSERPID,UOMSYSTEM,CURRENCY,PRIMARYCONTACTGUID,PRIMARYCONTACT,SALESPERSON,SALESPERSONRAVID,SALESPERSERPID,FOLLUWUP,FOLLOWUPSTATUS,LASTQUOTEGENERATEDBY,LASTQUOTEBYRAVID,LASTQUOTEBYERPID,LASTQUOTEGENERATEDON,LASTQUOTETEMPLATE,PAYMENTCONDITION1,DISCOUNTPERCENTAGE1,PAYMENTCONDITION2,DISCOUNTPERCENTAGE2,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.QUOTEGUID,src.QUOTENAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.STATUS,src.STATUSREASON,src.REVISIONNUMBER,src.EFFECTIVEFROM,src.EFFICTIVETO,src.SHIPPINGERPID,src.SHIPPINGADDRESS,src.BILLINGADDRESSERPID,src.BILLINGADDRESS,src.WAREHOUSEADDRESSERPID,src.WAREHOUSEADDRESS,src.INCOTERMERPID,src.INCOTERM,src.DESCRIPTION,src.UOMSYSERPID,src.UOMSYSTEM,src.CURRENCY,src.PRIMARYCONTACTGUID,src.PRIMARYCONTACT,src.SALESPERSON,src.SALESPERSONRAVID,src.SALESPERSERPID,src.FOLLUWUP,src.FOLLOWUPSTATUS,src.LASTQUOTEGENERATEDBY,src.LASTQUOTEBYRAVID,src.LASTQUOTEBYERPID,src.LASTQUOTEGENERATEDON,src.LASTQUOTETEMPLATE,src.PAYMENTCONDITION1,src.DISCOUNTPERCENTAGE1,src.PAYMENTCONDITION2,src.DISCOUNTPERCENTAGE2,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_RPCL AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_RPCL src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_RPCL)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.RPCLGUID = tgt.RPCLGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.RPCLGUID = src.RPCLGUID,tgt.RPCLNAME = src.RPCLNAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.OPPGUID = src.OPPGUID,tgt.OPPNAME = src.OPPNAME,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.CENTURIONNAME = src.CENTURIONNAME,tgt.CENTURIONRAVID = src.CENTURIONRAVID,tgt.CENTURIONPERSERPID = src.CENTURIONPERSERPID,tgt.CUSTPRICEINDICATION = src.CUSTPRICEINDICATION,tgt.TRANSACTIONCURR = src.TRANSACTIONCURR,tgt.COMPETITORMATERIAL = src.COMPETITORMATERIAL,tgt.MANUFSTARTDATE = src.MANUFSTARTDATE,tgt.MANUFCUSTOMERSEGMENT = src.MANUFCUSTOMERSEGMENT,tgt.KEYAPPLREQUIREMENTS = src.KEYAPPLREQUIREMENTS,tgt.PRIME = src.PRIME,tgt.PREUSE = src.PREUSE,tgt.POSTUSE = src.POSTUSE,tgt.FILLERTYPE = src.FILLERTYPE,tgt.FILLERCONTENTPERC = src.FILLERCONTENTPERC,tgt.COLOR = src.COLOR,tgt.UVSTABILIZATION = src.UVSTABILIZATION,tgt.ULCARD = src.ULCARD,tgt.HALOGENFREE = src.HALOGENFREE,tgt.FLAMMABLE = src.FLAMMABLE,tgt.KEYMATERIALREQUIREMENTS = src.KEYMATERIALREQUIREMENTS,tgt.UOM = src.UOM,tgt.EAQ = src.EAQ,tgt.CURRENCY = src.CURRENCY,tgt.REQUESTEDGROUP = src.REQUESTEDGROUP,tgt.REQUESTEDSUBGROUP = src.REQUESTEDSUBGROUP,tgt.REQUESTEDBRAND = src.REQUESTEDBRAND,tgt.REQUESTEDGRADE = src.REQUESTEDGRADE,tgt.APPLICATIONGUID = src.APPLICATIONGUID,tgt.APPLICATION = src.APPLICATION,tgt.ESTCLOSEDATE = src.ESTCLOSEDATE,tgt.INVESTIGATIONOUTCOME = src.INVESTIGATIONOUTCOME,tgt.INVESTIGATEDBY = src.INVESTIGATEDBY,tgt.INVESTBYRAVID = src.INVESTBYRAVID,tgt.INVESTBYPERSERPID = src.INVESTBYPERSERPID,tgt.INVESTIGATEDON = src.INVESTIGATEDON,tgt.CLOSEDATE = src.CLOSEDATE,tgt.CLOSEDESCRIPTION = src.CLOSEDESCRIPTION,tgt.RPCLSTATUSREASONCODE = src.RPCLSTATUSREASONCODE,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,RPCLGUID,RPCLNAME,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,OPPGUID,OPPNAME,STATUS,STATUSREASON,CENTURIONNAME,CENTURIONRAVID,CENTURIONPERSERPID,CUSTPRICEINDICATION,TRANSACTIONCURR,COMPETITORMATERIAL,MANUFSTARTDATE,MANUFCUSTOMERSEGMENT,KEYAPPLREQUIREMENTS,PRIME,PREUSE,POSTUSE,FILLERTYPE,FILLERCONTENTPERC,COLOR,UVSTABILIZATION,ULCARD,HALOGENFREE,FLAMMABLE,KEYMATERIALREQUIREMENTS,UOM,EAQ,CURRENCY,REQUESTEDGROUP,REQUESTEDSUBGROUP,REQUESTEDBRAND,REQUESTEDGRADE,APPLICATIONGUID,APPLICATION,ESTCLOSEDATE,INVESTIGATIONOUTCOME,INVESTIGATEDBY,INVESTBYRAVID,INVESTBYPERSERPID,INVESTIGATEDON,CLOSEDATE,CLOSEDESCRIPTION,RPCLSTATUSREASONCODE,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.RPCLGUID,src.RPCLNAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.OPPGUID,src.OPPNAME,src.STATUS,src.STATUSREASON,src.CENTURIONNAME,src.CENTURIONRAVID,src.CENTURIONPERSERPID,src.CUSTPRICEINDICATION,src.TRANSACTIONCURR,src.COMPETITORMATERIAL,src.MANUFSTARTDATE,src.MANUFCUSTOMERSEGMENT,src.KEYAPPLREQUIREMENTS,src.PRIME,src.PREUSE,src.POSTUSE,src.FILLERTYPE,src.FILLERCONTENTPERC,src.COLOR,src.UVSTABILIZATION,src.ULCARD,src.HALOGENFREE,src.FLAMMABLE,src.KEYMATERIALREQUIREMENTS,src.UOM,src.EAQ,src.CURRENCY,src.REQUESTEDGROUP,src.REQUESTEDSUBGROUP,src.REQUESTEDBRAND,src.REQUESTEDGRADE,src.APPLICATIONGUID,src.APPLICATION,src.ESTCLOSEDATE,src.INVESTIGATIONOUTCOME,src.INVESTIGATEDBY,src.INVESTBYRAVID,src.INVESTBYPERSERPID,src.INVESTIGATEDON,src.CLOSEDATE,src.CLOSEDESCRIPTION,src.RPCLSTATUSREASONCODE,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_SALESTEAMMEMBERS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_SALESTEAMMEMBERS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_SALESTEAMMEMBERS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src. = tgt.
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.SALESTEAMMEMBERGUID = src.SALESTEAMMEMBERGUID,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.SALESROLE = src.SALESROLE,tgt.TEAMMEMBER = src.TEAMMEMBER,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,SALESTEAMMEMBERGUID,ACCOUNTGUID,ACCOUNTNAME,ACCOUNTERPID,BUSINESSUNIT,SALESROLE,TEAMMEMBER,STATUS,STATUSREASON,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.SALESTEAMMEMBERGUID,src.ACCOUNTGUID,src.ACCOUNTNAME,src.ACCOUNTERPID,src.BUSINESSUNIT,src.SALESROLE,src.TEAMMEMBER,src.STATUS,src.STATUSREASON,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_SAMPLES AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_SAMPLES src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_SAMPLES)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.SALESTEAMMEMBERGUID = tgt.SALESTEAMMEMBERGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.SAMPLEGUID = src.SAMPLEGUID,tgt.SAMPLENAME = src.SAMPLENAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNTNAME = src.ACCOUNTNAME,tgt.PRODUCTNAME = src.PRODUCTNAME,tgt.PRODUCTSEGMENT = src.PRODUCTSEGMENT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.OPPORTUNITYNAME = src.OPPORTUNITYNAME,tgt.PRODUCTUSAGEGUID = src.PRODUCTUSAGEGUID,tgt.PRODUCTUSAGE = src.PRODUCTUSAGE,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.LENERPID = src.LENERPID,tgt.OLEERPID = src.OLEERPID,tgt.OLENAME = src.OLENAME,tgt.WRITEIN = src.WRITEIN,tgt.OPPORTUNITYPRODUCT = src.OPPORTUNITYPRODUCT,tgt.QUANTITY = src.QUANTITY,tgt.COMMENT = src.COMMENT,tgt.PRODUCTMANAGER = src.PRODUCTMANAGER,tgt.PRODUCTMANAGERRAVID = src.PRODUCTMANAGERRAVID,tgt.PRODUCTMANAGERPERSERPID = src.PRODUCTMANAGERPERSERPID,tgt.PRODUCTCOORDINATOR = src.PRODUCTCOORDINATOR,tgt.PRODCOORDINATORRAVID = src.PRODCOORDINATORRAVID,tgt.PRODCOORDINATORPERSERPID = src.PRODCOORDINATORPERSERPID,tgt.CSR = src.CSR,tgt.CSRRAVID = src.CSRRAVID,tgt.CSRPERSERPID = src.CSRPERSERPID,tgt.REQUESTEDDELIVERYON = src.REQUESTEDDELIVERYON,tgt.INCOTERMERPID = src.INCOTERMERPID,tgt.INCOTERM = src.INCOTERM,tgt.SHIPPINGADDERPID = src.SHIPPINGADDERPID,tgt.SHIPPINGADDRESS = src.SHIPPINGADDRESS,tgt.BILLINGADDRERPID = src.BILLINGADDRERPID,tgt.BILLINGADDRESS = src.BILLINGADDRESS,tgt.REVIEWEDBY = src.REVIEWEDBY,tgt.REVIEWEDRAVID = src.REVIEWEDRAVID,tgt.REVIEWEDPERSERPID = src.REVIEWEDPERSERPID,tgt.REVIEWEDON = src.REVIEWEDON,tgt.REVIEWOUTCOME = src.REVIEWOUTCOME,tgt.MOTIVATION = src.MOTIVATION,tgt.CUSTOMERAPPROVAL = src.CUSTOMERAPPROVAL,tgt.FEEDBACKCOMMENT = src.FEEDBACKCOMMENT,tgt.CONFIRMEDDELIVERYDATE = src.CONFIRMEDDELIVERYDATE,tgt.ORDERNUMBER = src.ORDERNUMBER,tgt.OHMSTATUS = src.OHMSTATUS,tgt.PRODUCT = src.PRODUCT,tgt.WRITEINPRODUCT = src.WRITEINPRODUCT,tgt.PRODUCTERPID = src.PRODUCTERPID,tgt.CUSTOMERERPID = src.CUSTOMERERPID,tgt.PRICEPERUNIT = src.PRICEPERUNIT,tgt.CURRENCY = src.CURRENCY,tgt.FREIGHTAMOUNT = src.FREIGHTAMOUNT,tgt.EAQSI = src.EAQSI,tgt.EAQUS = src.EAQUS,tgt.UOMSYSTEMERPID = src.UOMSYSTEMERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.UOM = src.UOM,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.CREATEDINOHMON = src.CREATEDINOHMON,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.FOLLOWUPMODE = src.FOLLOWUPMODE,tgt.FOLLOWUPSTATUS = src.FOLLOWUPSTATUS,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,SAMPLEGUID,SAMPLENAME,ACCOUNTGUID,ACCOUNTERPID,ACCOUNTNAME,PRODUCTNAME,PRODUCTSEGMENT,STATUS,STATUSREASON,OPPORTUNITYGUID,OPPORTUNITYNAME,PRODUCTUSAGEGUID,PRODUCTUSAGE,BUSINESSUNIT,LENERPID,OLEERPID,OLENAME,WRITEIN,OPPORTUNITYPRODUCT,QUANTITY,COMMENT,PRODUCTMANAGER,PRODUCTMANAGERRAVID,PRODUCTMANAGERPERSERPID,PRODUCTCOORDINATOR,PRODCOORDINATORRAVID,PRODCOORDINATORPERSERPID,CSR,CSRRAVID,CSRPERSERPID,REQUESTEDDELIVERYON,INCOTERMERPID,INCOTERM,SHIPPINGADDERPID,SHIPPINGADDRESS,BILLINGADDRERPID,BILLINGADDRESS,REVIEWEDBY,REVIEWEDRAVID,REVIEWEDPERSERPID,REVIEWEDON,REVIEWOUTCOME,MOTIVATION,CUSTOMERAPPROVAL,FEEDBACKCOMMENT,CONFIRMEDDELIVERYDATE,ORDERNUMBER,OHMSTATUS,PRODUCT,WRITEINPRODUCT,PRODUCTERPID,CUSTOMERERPID,PRICEPERUNIT,CURRENCY,FREIGHTAMOUNT,EAQSI,EAQUS,UOMSYSTEMERPID,UOMSYSTEM,UOM,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,CREATEDINOHMON,OWNER,OWNERRAVID,OWNERPERSERPID,FOLLOWUPMODE,FOLLOWUPSTATUS,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.SAMPLEGUID,src.SAMPLENAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNTNAME,src.PRODUCTNAME,src.PRODUCTSEGMENT,src.STATUS,src.STATUSREASON,src.OPPORTUNITYGUID,src.OPPORTUNITYNAME,src.PRODUCTUSAGEGUID,src.PRODUCTUSAGE,src.BUSINESSUNIT,src.LENERPID,src.OLEERPID,src.OLENAME,src.WRITEIN,src.OPPORTUNITYPRODUCT,src.QUANTITY,src.COMMENT,src.PRODUCTMANAGER,src.PRODUCTMANAGERRAVID,src.PRODUCTMANAGERPERSERPID,src.PRODUCTCOORDINATOR,src.PRODCOORDINATORRAVID,src.PRODCOORDINATORPERSERPID,src.CSR,src.CSRRAVID,src.CSRPERSERPID,src.REQUESTEDDELIVERYON,src.INCOTERMERPID,src.INCOTERM,src.SHIPPINGADDERPID,src.SHIPPINGADDRESS,src.BILLINGADDRERPID,src.BILLINGADDRESS,src.REVIEWEDBY,src.REVIEWEDRAVID,src.REVIEWEDPERSERPID,src.REVIEWEDON,src.REVIEWOUTCOME,src.MOTIVATION,src.CUSTOMERAPPROVAL,src.FEEDBACKCOMMENT,src.CONFIRMEDDELIVERYDATE,src.ORDERNUMBER,src.OHMSTATUS,src.PRODUCT,src.WRITEINPRODUCT,src.PRODUCTERPID,src.CUSTOMERERPID,src.PRICEPERUNIT,src.CURRENCY,src.FREIGHTAMOUNT,src.EAQSI,src.EAQUS,src.UOMSYSTEMERPID,src.UOMSYSTEM,src.UOM,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.CREATEDINOHMON,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.FOLLOWUPMODE,src.FOLLOWUPSTATUS,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_SOURCE AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_SOURCE src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_SOURCE)) AS src
		ON src.id = tgt.ID
	WHEN MATCHED THEN 
UPDATE
SET tgt.ID = src.ID,tgt.ENVIRONMENT = src.ENVIRONMENT,tgt.SOURCEID = src.SOURCEID,tgt.SOURCE = src.SOURCE,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDON = src.CREATEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDON = src.MODIFIEDON	WHEN NOT MATCHED THEN
INSERT
	(ID,ENVIRONMENT,SOURCEID,SOURCE,CREATEDBY,CREATEDON,MODIFIEDBY,MODIFIEDON) 
VALUES 
(src.ID,src.ENVIRONMENT,src.SOURCEID,src.SOURCE,src.CREATEDBY,src.CREATEDON,src.MODIFIEDBY,src.MODIFIEDON);

MERGE
INTO
	GAUSS_BIGD.MSCRM_TASKS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_TASKS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_TASKS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.ACTIVITYGUID = tgt.ACTIVITYGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.ACTIVITYGUID = src.ACTIVITYGUID,tgt.ACTIVITYTYPE = src.ACTIVITYTYPE,tgt.REGARDINGENTITYGUID = src.REGARDINGENTITYGUID,tgt.REGARDINGENTITY = src.REGARDINGENTITY,tgt.REGARDING = src.REGARDING,tgt.REGARDINGACCOUNT = src.REGARDINGACCOUNT,tgt.BUSINESSUNIT = src.BUSINESSUNIT,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.PRIORITY = src.PRIORITY,tgt.SUBJECT = src.SUBJECT,tgt.DESCRIPTION = src.DESCRIPTION,tgt.SCHEDULEDSTART = src.SCHEDULEDSTART,tgt.SCHEDULEDDURATION = src.SCHEDULEDDURATION,tgt.SCHEDULEDEND = src.SCHEDULEDEND,tgt.ACTUALSTART = src.ACTUALSTART,tgt.ACTUALDURATION = src.ACTUALDURATION,tgt.ACTUALEND = src.ACTUALEND,tgt.ACTIVITYREPORTGUID = src.ACTIVITYREPORTGUID,tgt.ACTIVITYREPORT = src.ACTIVITYREPORT,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,ACTIVITYGUID,ACTIVITYTYPE,REGARDINGENTITYGUID,REGARDINGENTITY,REGARDING,REGARDINGACCOUNT,BUSINESSUNIT,STATUS,STATUSREASON,PRIORITY,SUBJECT,DESCRIPTION,SCHEDULEDSTART,SCHEDULEDDURATION,SCHEDULEDEND,ACTUALSTART,ACTUALDURATION,ACTUALEND,ACTIVITYREPORTGUID,ACTIVITYREPORT,OWNER,OWNERRAVID,OWNERPERSERPID,CREATEDON,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,MODIFIEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.ACTIVITYGUID,src.ACTIVITYTYPE,src.REGARDINGENTITYGUID,src.REGARDINGENTITY,src.REGARDING,src.REGARDINGACCOUNT,src.BUSINESSUNIT,src.STATUS,src.STATUSREASON,src.PRIORITY,src.SUBJECT,src.DESCRIPTION,src.SCHEDULEDSTART,src.SCHEDULEDDURATION,src.SCHEDULEDEND,src.ACTUALSTART,src.ACTUALDURATION,src.ACTUALEND,src.ACTIVITYREPORTGUID,src.ACTIVITYREPORT,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.CREATEDON,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.MODIFIEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MAXCHANGEDDATE);

MERGE
INTO
	GAUSS_BIGD.MSCRM_USAGEDETAILS AS tgt
		USING (
	SELECT
		src.*
	FROM
		fed_mscrm_dev.MSCRM_USAGEDETAILS src
	WHERE
				to_timestamp(to_char(MAXCHANGEDDATE,'YYYY-MM-DD-HH24:MI:SS.FF6'),'YYYY-MM-DD-HH24:MI:SS.FF6') >= (
		SELECT
			DATE(NVL(MAX(MAXCHANGEDDATE),TO_DATE('1000-01-01','YYYY-MM-DD')))
		FROM GAUSS_BIGD.MSCRM_USAGEDETAILS)) AS src
		ON src.sourceid = tgt.SOURCEID
		AND src.USAGEDETAILGUID = tgt.USAGEDETAILGUID
	WHEN MATCHED THEN 
UPDATE
SET tgt.URL = src.URL,tgt.SOURCEID = src.SOURCEID,tgt.USAGEDETAILGUID = src.USAGEDETAILGUID,tgt.STATUS = src.STATUS,tgt.STATUSREASON = src.STATUSREASON,tgt.USAGEDETAILNAME = src.USAGEDETAILNAME,tgt.ACCOUNTGUID = src.ACCOUNTGUID,tgt.ACCOUNTERPID = src.ACCOUNTERPID,tgt.ACCOUNT = src.ACCOUNT,tgt.PRODUCTUSAGEGUID = src.PRODUCTUSAGEGUID,tgt.PRODUCTUSAGE = src.PRODUCTUSAGE,tgt.COMPETITORSHARES = src.COMPETITORSHARES,tgt.APPLICATIONGUID = src.APPLICATIONGUID,tgt.APPLICATIONNAME = src.APPLICATIONNAME,tgt.MRFPROCEDURE = src.MRFPROCEDURE,tgt.OPPORTUNITYGUID = src.OPPORTUNITYGUID,tgt.LATESTSHARESHIFTATTEMPT = src.LATESTSHARESHIFTATTEMPT,tgt.APPLICATIONSUMMARY = src.APPLICATIONSUMMARY,tgt.SHARETYPE = src.SHARETYPE,tgt.EAQ = src.EAQ,tgt.COMPETITORGUID = src.COMPETITORGUID,tgt.SUPPLIERERPID = src.SUPPLIERERPID,tgt.SUPPLIEDBY = src.SUPPLIEDBY,tgt.BRANDERPID = src.BRANDERPID,tgt.BRAND = src.BRAND,tgt.GRADE = src.GRADE,tgt.COMMENT = src.COMMENT,tgt.UOMSYSTEMERPID = src.UOMSYSTEMERPID,tgt.UOMSYSTEM = src.UOMSYSTEM,tgt.UOM = src.UOM,tgt.EAQSI = src.EAQSI,tgt.EAQUS = src.EAQUS,tgt.CREATEDBY = src.CREATEDBY,tgt.CREATEDRAVID = src.CREATEDRAVID,tgt.CREATEDPERSERPID = src.CREATEDPERSERPID,tgt.CREATEDON = src.CREATEDON,tgt.MODIFIEDBY = src.MODIFIEDBY,tgt.MODIFIEDRAVID = src.MODIFIEDRAVID,tgt.MODIFIEDPERSERPID = src.MODIFIEDPERSERPID,tgt.MODIFIEDON = src.MODIFIEDON,tgt.OWNER = src.OWNER,tgt.OWNERRAVID = src.OWNERRAVID,tgt.OWNERPERSERPID = src.OWNERPERSERPID,tgt.MAXCHANGEDDATE = src.MAXCHANGEDDATE	WHEN NOT MATCHED THEN
INSERT
	(URL,SOURCEID,USAGEDETAILGUID,STATUS,STATUSREASON,USAGEDETAILNAME,ACCOUNTGUID,ACCOUNTERPID,ACCOUNT,PRODUCTUSAGEGUID,PRODUCTUSAGE,COMPETITORSHARES,APPLICATIONGUID,APPLICATIONNAME,MRFPROCEDURE,OPPORTUNITYGUID,LATESTSHARESHIFTATTEMPT,APPLICATIONSUMMARY,SHARETYPE,EAQ,COMPETITORGUID,SUPPLIERERPID,SUPPLIEDBY,BRANDERPID,BRAND,GRADE,COMMENT,UOMSYSTEMERPID,UOMSYSTEM,UOM,EAQSI,EAQUS,CREATEDBY,CREATEDRAVID,CREATEDPERSERPID,CREATEDON,MODIFIEDBY,MODIFIEDRAVID,MODIFIEDPERSERPID,MODIFIEDON,OWNER,OWNERRAVID,OWNERPERSERPID,MAXCHANGEDDATE) 
VALUES 
(src.URL,src.SOURCEID,src.USAGEDETAILGUID,src.STATUS,src.STATUSREASON,src.USAGEDETAILNAME,src.ACCOUNTGUID,src.ACCOUNTERPID,src.ACCOUNT,src.PRODUCTUSAGEGUID,src.PRODUCTUSAGE,src.COMPETITORSHARES,src.APPLICATIONGUID,src.APPLICATIONNAME,src.MRFPROCEDURE,src.OPPORTUNITYGUID,src.LATESTSHARESHIFTATTEMPT,src.APPLICATIONSUMMARY,src.SHARETYPE,src.EAQ,src.COMPETITORGUID,src.SUPPLIERERPID,src.SUPPLIEDBY,src.BRANDERPID,src.BRAND,src.GRADE,src.COMMENT,src.UOMSYSTEMERPID,src.UOMSYSTEM,src.UOM,src.EAQSI,src.EAQUS,src.CREATEDBY,src.CREATEDRAVID,src.CREATEDPERSERPID,src.CREATEDON,src.MODIFIEDBY,src.MODIFIEDRAVID,src.MODIFIEDPERSERPID,src.MODIFIEDON,src.OWNER,src.OWNERRAVID,src.OWNERPERSERPID,src.MAXCHANGEDDATE);
